# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    trusted_proxies: "%env(csv:SYMFONY_TRUSTED_PROXIES)%"
    trusted_headers:
        - x-forwarded-for
        - x-forwarded-host
        - x-forwarded-proto
        - x-forwarded-port

    # Note that the session will be started ONLY if you read or write from it.
    session:
        # Trỏ tới service ID mà chúng ta vừa tạo ở Bước 1
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

        # Các cấu hình khác giữ nguyên hoặc chỉnh tùy ý
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
