stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true # Kích hoạt tính năng timestamp
            softdeleteable: true # Kích hoạt tính năng softdelete
