services:
    be-php:
        container_name: workhub_be_php
        networks:
            - default
            - dbnet

    be-nginx:
        container_name: workhub_be_nginx
        networks:
            - default
            - edge

    fe-nginx:
        container_name: workhub_fe_nginx
        networks:
            - default
            - edge

    messenger:
        container_name: workhub_messenger
        networks:
            - default
            - dbnet

    scheduler:
        container_name: workhub_scheduler
        networks:
            - default
            - dbnet

    mercure:
        container_name: workhub_mercure
        environment:
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins https://workhub.huybach02.io.vn https://workhub-api.huybach02.io.vn https://workhub-mercure.huybach02.io.vn
        networks:
            - default
            - edge

networks:
    edge:
        external: true

    dbnet:
        external: true
