<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625131545 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, symbol VARCHAR(255) DEFAULT NULL, status INT DEFAULT 1, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DCBB0C5377153098 ON unit (code)');
        $this->addSql('CREATE INDEX idx_attendance_employee_date ON attendance (employee_id, work_date)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BRANCH_CODE ON branch (code) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORY_SLUG ON category (slug) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DEPARTMENT_MA_BO_PHAN ON department (ma_bo_phan) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EE5415EC8C55589B ON general_setting (ten_cau_hinh)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BDB2E1B977153098 ON holiday_schedule (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE4B9114606E7130 ON login_device (device_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B6BD307F77153098 ON message (code)');
        $this->addSql('CREATE INDEX idx_notification_to_id ON notification (to_id)');
        $this->addSql('CREATE INDEX idx_notification_to_id_seen ON notification (to_id, seen)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_CODE ON "position" (code) WHERE deleted_at IS NULL');
        $this->addSql('CREATE INDEX idx_request_status ON request (status)');
        $this->addSql('CREATE INDEX idx_request_type ON request (type)');
        $this->addSql('DROP INDEX uniq_user_ma_nhan_vien');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_PHONE ON "user" (phone) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_MA_NHAN_VIEN ON "user" (ma_nhan_vien) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WAREHOUSE_CODE ON warehouse (code) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE unit');
        $this->addSql('DROP INDEX idx_attendance_employee_date');
        $this->addSql('DROP INDEX UNIQ_BRANCH_CODE');
        $this->addSql('DROP INDEX UNIQ_CATEGORY_SLUG');
        $this->addSql('DROP INDEX UNIQ_DEPARTMENT_MA_BO_PHAN');
        $this->addSql('DROP INDEX UNIQ_EE5415EC8C55589B');
        $this->addSql('DROP INDEX UNIQ_BDB2E1B977153098');
        $this->addSql('DROP INDEX UNIQ_FE4B9114606E7130');
        $this->addSql('DROP INDEX UNIQ_B6BD307F77153098');
        $this->addSql('DROP INDEX idx_notification_to_id');
        $this->addSql('DROP INDEX idx_notification_to_id_seen');
        $this->addSql('DROP INDEX UNIQ_POSITION_CODE');
        $this->addSql('DROP INDEX idx_request_status');
        $this->addSql('DROP INDEX idx_request_type');
        $this->addSql('DROP INDEX UNIQ_8D93D649E7927C74');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('DROP INDEX UNIQ_USER_MA_NHAN_VIEN');
        $this->addSql('DROP INDEX UNIQ_USER_PHONE');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_ma_nhan_vien ON "user" (ma_nhan_vien) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_WAREHOUSE_CODE');
    }
}
