<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316124923 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, last_message TEXT DEFAULT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_draft BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, bo_phan_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A8E26E9D7208CD7 ON conversation (bo_phan_id)');
        $this->addSql('COMMENT ON COLUMN conversation.type IS \'private, group\'');
        $this->addSql('CREATE TABLE conversation_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unread_count INT DEFAULT 0 NOT NULL, last_read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_online BOOLEAN DEFAULT false NOT NULL, last_online_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_muted BOOLEAN DEFAULT false NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, left_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, conversation_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5AECB5559AC0396 ON conversation_user (conversation_id)');
        $this->addSql('CREATE INDEX IDX_5AECB555A76ED395 ON conversation_user (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_conversation_user ON conversation_user (conversation_id, user_id)');
        $this->addSql('CREATE TABLE department (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ma_bo_phan VARCHAR(255) NOT NULL, ten_bo_phan VARCHAR(255) NOT NULL, status INT DEFAULT 1 NOT NULL, phan_quyen JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, quan_ly_bo_phan_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD1DE18A6A86E473 ON department (quan_ly_bo_phan_id)');
        $this->addSql('CREATE TABLE folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, parent_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ECA209CD727ACA70 ON folder (parent_id)');
        $this->addSql('CREATE INDEX IDX_ECA209CD7E3C61F9 ON folder (owner_id)');
        $this->addSql('CREATE TABLE general_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ten_cau_hinh VARCHAR(255) NOT NULL, gia_tri VARCHAR(255) NOT NULL, mo_ta VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, entity_type VARCHAR(255) NOT NULL, entity_id INT NOT NULL, type VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE import_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(255) NOT NULL, file_name VARCHAR(255) DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, total_rows INT DEFAULT NULL, success_rows INT DEFAULT NULL, error_rows INT DEFAULT NULL, error_details JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE keep_alive_db (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, time VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE login_device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, device_key VARCHAR(255) NOT NULL, user_id INT NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT DEFAULT NULL, folder_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10C7E3C61F9 ON media (owner_id)');
        $this->addSql('CREATE INDEX IDX_6A2CA10C162CB942 ON media (folder_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) DEFAULT NULL, content TEXT DEFAULT NULL, images JSON DEFAULT NULL, files JSON DEFAULT NULL, is_seen BOOLEAN DEFAULT false, seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, conversation_id INT DEFAULT NULL, sender_id INT DEFAULT NULL, receiver_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FCD53EDB6 ON message (receiver_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, from_id INT NOT NULL, to_id INT NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, icon VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, seen BOOLEAN DEFAULT false NOT NULL, link VARCHAR(255) DEFAULT NULL, is_created BOOLEAN DEFAULT false NOT NULL, type_notification VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON DEFAULT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(20) DEFAULT NULL, gender VARCHAR(255) DEFAULT NULL, province VARCHAR(255) DEFAULT NULL, district VARCHAR(255) DEFAULT NULL, ward VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, birthday VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status INT DEFAULT 1 NOT NULL, is_ngoai_gio INT DEFAULT 0 NOT NULL, hinh_thuc_lam_viec INT DEFAULT 1 NOT NULL, bo_phan_id INT DEFAULT NULL, ma_nhan_vien VARCHAR(50) DEFAULT NULL, cmnd VARCHAR(20) DEFAULT NULL, ngay_cap_cmnd VARCHAR(20) DEFAULT NULL, noi_cap_cmnd VARCHAR(255) DEFAULT NULL, ngay_vao_lam VARCHAR(20) DEFAULT NULL, remember_token VARCHAR(100) DEFAULT NULL, is_first_login INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6499D6C73BF ON "user" (ma_nhan_vien)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".status IS \'1: active, 0: inactive\'');
        $this->addSql('COMMENT ON COLUMN "user".is_ngoai_gio IS \'0: cho phep ngoai gio, 1: khong cho phep ngoai gio\'');
        $this->addSql('COMMENT ON COLUMN "user".hinh_thuc_lam_viec IS \'1: full time, 2: part time\'');
        $this->addSql('COMMENT ON COLUMN "user".is_first_login IS \'0: tai khoan da doi mat khau, 1: tai khoan dang nhap lan dau tien\'');
        $this->addSql('CREATE TABLE user_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, bo_phan_id INT NOT NULL, phan_quyen JSON DEFAULT NULL, is_default BOOLEAN DEFAULT false, is_manager BOOLEAN DEFAULT false, is_custom BOOLEAN DEFAULT false, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE work_shift (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gio_bat_dau VARCHAR(255) NOT NULL, gio_ket_thuc VARCHAR(255) NOT NULL, ghi_chu VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, thoi_gian_lam_viec_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8DF0406A2DBE3FA2 ON work_shift (thoi_gian_lam_viec_id)');
        $this->addSql('CREATE TABLE working_time (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, thu VARCHAR(255) NOT NULL, gio_bat_dau VARCHAR(255) NOT NULL, gio_ket_thuc VARCHAR(255) NOT NULL, ghi_chu VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9D7208CD7 FOREIGN KEY (bo_phan_id) REFERENCES department (id)');
        $this->addSql('ALTER TABLE conversation_user ADD CONSTRAINT FK_5AECB5559AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_user ADD CONSTRAINT FK_5AECB555A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A6A86E473 FOREIGN KEY (quan_ly_bo_phan_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE folder ADD CONSTRAINT FK_ECA209CD727ACA70 FOREIGN KEY (parent_id) REFERENCES folder (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folder ADD CONSTRAINT FK_ECA209CD7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C162CB942 FOREIGN KEY (folder_id) REFERENCES folder (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FCD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE work_shift ADD CONSTRAINT FK_8DF0406A2DBE3FA2 FOREIGN KEY (thoi_gian_lam_viec_id) REFERENCES working_time (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9D7208CD7');
        $this->addSql('ALTER TABLE conversation_user DROP CONSTRAINT FK_5AECB5559AC0396');
        $this->addSql('ALTER TABLE conversation_user DROP CONSTRAINT FK_5AECB555A76ED395');
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18A6A86E473');
        $this->addSql('ALTER TABLE folder DROP CONSTRAINT FK_ECA209CD727ACA70');
        $this->addSql('ALTER TABLE folder DROP CONSTRAINT FK_ECA209CD7E3C61F9');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C7E3C61F9');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C162CB942');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FCD53EDB6');
        $this->addSql('ALTER TABLE work_shift DROP CONSTRAINT FK_8DF0406A2DBE3FA2');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE conversation_user');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE folder');
        $this->addSql('DROP TABLE general_setting');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE import_log');
        $this->addSql('DROP TABLE keep_alive_db');
        $this->addSql('DROP TABLE login_device');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_permission');
        $this->addSql('DROP TABLE work_shift');
        $this->addSql('DROP TABLE working_time');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
