<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618132146 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE branch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address TEXT DEFAULT NULL, status BOOLEAN DEFAULT true, note TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE warehouse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, status BOOLEAN DEFAULT true, note TEXT DEFAULT NULL, branch_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ECB38BFCDCD6CC49 ON warehouse (branch_id)');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id)');
        $this->addSql('DROP INDEX idx_a338a92a58742ef6_ba48ab4e_6a093d5a');
        $this->addSql('COMMENT ON COLUMN attendance.status IS \'scheduled,on_time,late,early_leave,absent\'');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT FK_ECB38BFCDCD6CC49');
        $this->addSql('DROP TABLE branch');
        $this->addSql('DROP TABLE warehouse');
        $this->addSql('COMMENT ON COLUMN attendance.status IS \'on_time,late,early_leave\'');
        $this->addSql('CREATE INDEX idx_a338a92a58742ef6_ba48ab4e_6a093d5a ON attendance (status, reminder_at, reminded_at)');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
    }
}
