<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705134451 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE attendance (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              attendance_type VARCHAR(255) DEFAULT NULL,
              work_date DATE DEFAULT NULL,
              time_attendance VARCHAR(255) DEFAULT NULL,
              work_schedule_start_time VARCHAR(255) DEFAULT NULL,
              work_schedule_end_time VARCHAR(255) DEFAULT NULL,
              reminder_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              reminded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              status VARCHAR(255) DEFAULT NULL,
              validation_status VARCHAR(255) DEFAULT NULL,
              work_type VARCHAR(255) DEFAULT NULL,
              config_snapshot JSON DEFAULT NULL,
              work_schedule_snapshot JSON DEFAULT NULL,
              photo_path VARCHAR(255) DEFAULT NULL,
              late_minute INT DEFAULT NULL,
              early_leave_minute INT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              employee_id INT DEFAULT NULL,
              work_shift_assignment_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6DE30D918C03F15C ON attendance (employee_id)');
        $this->addSql('CREATE INDEX IDX_6DE30D91655C1043 ON attendance (work_shift_assignment_id)');
        $this->addSql('CREATE INDEX idx_attendance_employee_date ON attendance (employee_id, work_date)');
        $this->addSql('COMMENT ON COLUMN attendance.attendance_type IS \'check_in/check_out\'');
        $this->addSql('COMMENT ON COLUMN attendance.status IS \'scheduled,on_time,late,early_leave,absent\'');
        $this->addSql('COMMENT ON COLUMN attendance.validation_status IS \'invalid/valid\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE attendance_log (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              validation_status VARCHAR(255) DEFAULT NULL,
              validation_reason VARCHAR(255) DEFAULT NULL,
              ip_address VARCHAR(255) DEFAULT NULL,
              latitude VARCHAR(255) DEFAULT NULL,
              longtitude VARCHAR(255) DEFAULT NULL,
              gps_accuracy_meter INT DEFAULT NULL,
              device_id INT DEFAULT NULL,
              qr_token VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              attendance_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_8920D967163DDA15 ON attendance_log (attendance_id)');
        $this->addSql('COMMENT ON COLUMN attendance_log.validation_status IS \'invalid/valid\'');
        $this->addSql('COMMENT ON COLUMN attendance_log.validation_reason IS \'lưu code của reason\'');
        $this->addSql('COMMENT ON COLUMN attendance_log.latitude IS \'vĩ độ\'');
        $this->addSql('COMMENT ON COLUMN attendance_log.longtitude IS \'kinh độ\'');
        $this->addSql('COMMENT ON COLUMN attendance_log.gps_accuracy_meter IS \'khoảng cách\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE branch (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) DEFAULT NULL,
              type VARCHAR(255) DEFAULT NULL,
              name VARCHAR(255) DEFAULT NULL,
              phone VARCHAR(255) DEFAULT NULL,
              email VARCHAR(255) DEFAULT NULL,
              address TEXT DEFAULT NULL,
              status BOOLEAN DEFAULT true,
              note TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BRANCH_CODE ON branch (code) WHERE deleted_at IS NULL');
        $this->addSql(<<<'SQL'
            CREATE TABLE cache_persist (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              key VARCHAR(255) NOT NULL,
              value TEXT NOT NULL,
              expire_at INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE category (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              slug VARCHAR(255) NOT NULL,
              type VARCHAR(255) NOT NULL,
              path VARCHAR(1000) DEFAULT NULL,
              level INT NOT NULL,
              position INT NOT NULL,
              is_active BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              parent_id BIGINT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_64C19C1727ACA70 ON category (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORY_SLUG ON category (slug) WHERE deleted_at IS NULL');
        $this->addSql(<<<'SQL'
            CREATE TABLE conversation (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type VARCHAR(255) DEFAULT NULL,
              name VARCHAR(255) DEFAULT NULL,
              avatar VARCHAR(255) DEFAULT NULL,
              last_message TEXT DEFAULT NULL,
              last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              is_draft BOOLEAN DEFAULT true NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              bo_phan_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A8E26E9D7208CD7 ON conversation (bo_phan_id)');
        $this->addSql('COMMENT ON COLUMN conversation.type IS \'private, group\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE conversation_user (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              unread_count INT DEFAULT 0 NOT NULL,
              last_read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              is_online BOOLEAN DEFAULT false NOT NULL,
              last_online_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              is_muted BOOLEAN DEFAULT false NOT NULL,
              joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              left_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              conversation_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_5AECB5559AC0396 ON conversation_user (conversation_id)');
        $this->addSql('CREATE INDEX IDX_5AECB555A76ED395 ON conversation_user (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_conversation_user ON conversation_user (conversation_id, user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE department (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              ma_bo_phan VARCHAR(255) NOT NULL,
              ten_bo_phan VARCHAR(255) NOT NULL,
              status INT DEFAULT 1 NOT NULL,
              ghi_chu TEXT DEFAULT NULL,
              phan_quyen JSON DEFAULT NULL,
              quan_ly_bo_phan JSON DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_DEPARTMENT_MA_BO_PHAN ON department (ma_bo_phan)
            WHERE
              deleted_at IS NULL
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE fixed_schedule (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              day_of_week INT DEFAULT NULL,
              start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              fixed_schedule_group_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_65FA44A116AB3DE1 ON fixed_schedule (fixed_schedule_group_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE fixed_schedule_group (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              start_date DATE DEFAULT NULL,
              end_date DATE DEFAULT NULL,
              type VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              member_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_3F0C6B937597D3FE ON fixed_schedule_group (member_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE fixed_schedule_override (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              start_date DATE DEFAULT NULL,
              end_date DATE DEFAULT NULL,
              start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              type VARCHAR(255) DEFAULT NULL,
              reason TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              member_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6AFCE2437597D3FE ON fixed_schedule_override (member_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE folder (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              parent_id INT DEFAULT NULL,
              owner_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_ECA209CD727ACA70 ON folder (parent_id)');
        $this->addSql('CREATE INDEX IDX_ECA209CD7E3C61F9 ON folder (owner_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE general_setting (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              ten_cau_hinh VARCHAR(255) NOT NULL,
              gia_tri VARCHAR(255) NOT NULL,
              mo_ta VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EE5415EC8C55589B ON general_setting (ten_cau_hinh)');
        $this->addSql(<<<'SQL'
            CREATE TABLE holiday_schedule (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) DEFAULT NULL,
              name VARCHAR(255) DEFAULT NULL,
              year VARCHAR(255) DEFAULT NULL,
              date DATE DEFAULT NULL,
              status BOOLEAN DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BDB2E1B977153098 ON holiday_schedule (code)');
        $this->addSql(<<<'SQL'
            CREATE TABLE image (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              path VARCHAR(255) NOT NULL,
              entity_type VARCHAR(255) NOT NULL,
              entity_id INT NOT NULL,
              type VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE import_log (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              entity_type VARCHAR(255) NOT NULL,
              file_name VARCHAR(255) DEFAULT NULL,
              file_path VARCHAR(255) DEFAULT NULL,
              status VARCHAR(255) DEFAULT NULL,
              total_rows INT DEFAULT NULL,
              success_rows INT DEFAULT NULL,
              error_rows INT DEFAULT NULL,
              error_details JSON DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE keep_alive_db (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              time VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE leave_schedule (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type VARCHAR(255) DEFAULT NULL,
              start_datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              end_datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              status VARCHAR(255) DEFAULT NULL,
              reason TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              member_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_641039587597D3FE ON leave_schedule (member_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE login_device (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              device_key VARCHAR(255) NOT NULL,
              user_id INT NOT NULL,
              metadata JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE4B9114606E7130 ON login_device (device_key)');
        $this->addSql(<<<'SQL'
            CREATE TABLE media (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              path VARCHAR(255) NOT NULL,
              original_name VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              owner_id INT DEFAULT NULL,
              folder_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6A2CA10C7E3C61F9 ON media (owner_id)');
        $this->addSql('CREATE INDEX IDX_6A2CA10C162CB942 ON media (folder_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) NOT NULL,
              name VARCHAR(255) NOT NULL,
              type VARCHAR(50) NOT NULL,
              profit NUMERIC(10, 2) DEFAULT NULL,
              description TEXT DEFAULT NULL,
              notes TEXT DEFAULT NULL,
              stock_alert_quantity NUMERIC(10, 2) DEFAULT NULL,
              status SMALLINT DEFAULT 1 NOT NULL,
              is_single_unit BOOLEAN DEFAULT false NOT NULL,
              finished_product_source VARCHAR(50) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              category_id BIGINT DEFAULT NULL,
              base_unit_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_D043D1A412469DE2 ON merchandise (category_id)');
        $this->addSql('CREATE INDEX IDX_D043D1A4CCBBC969 ON merchandise (base_unit_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MERCHANDISE_CODE ON merchandise (code) WHERE deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN merchandise.code IS \'Mã hàng hóa\'');
        $this->addSql('COMMENT ON COLUMN merchandise.name IS \'Tên hàng hóa\'');
        $this->addSql('COMMENT ON COLUMN merchandise.type IS \'Loại hàng hóa (finished_product, ingredient)\'');
        $this->addSql('COMMENT ON COLUMN merchandise.profit IS \'% lợi nhuận mặc định\'');
        $this->addSql('COMMENT ON COLUMN merchandise.description IS \'Mô tả\'');
        $this->addSql('COMMENT ON COLUMN merchandise.notes IS \'Ghi chú\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise.stock_alert_quantity IS 'Số lượng cảnh báo theo base unit'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise.status IS \'Trạng thái (1 active, 0 inactive)\'');
        $this->addSql('COMMENT ON COLUMN merchandise.is_single_unit IS \'Chỉ có 1 đơn vị tính\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise.finished_product_source IS 'Nguồn thành phẩm (supplier, production)'
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise_provider (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              unit_config_mode VARCHAR(50) DEFAULT 'general' NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              merchandise_id INT NOT NULL,
              provider_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_A826E055CFC6D428 ON merchandise_provider (merchandise_id)');
        $this->addSql('CREATE INDEX IDX_A826E055A53A8AA ON merchandise_provider (provider_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_provider.unit_config_mode IS \'general hoặc custom\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise_provider_price (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              unit_label_snapshot VARCHAR(255) DEFAULT NULL,
              factor_to_base_snapshot NUMERIC(10, 4) DEFAULT NULL,
              price NUMERIC(15, 2) NOT NULL,
              discount_rate NUMERIC(5, 2) DEFAULT '0.00',
              discount_amount NUMERIC(15, 2) DEFAULT '0.00',
              price_after_discount NUMERIC(15, 2) NOT NULL,
              currency VARCHAR(10) DEFAULT 'VND' NOT NULL,
              effective_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              effective_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              is_default BOOLEAN DEFAULT false NOT NULL,
              status SMALLINT DEFAULT 1 NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              merchandise_provider_id INT NOT NULL,
              unit_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_66556CE480455FD2 ON merchandise_provider_price (merchandise_provider_id)');
        $this->addSql('CREATE INDEX IDX_66556CE4F8BD700D ON merchandise_provider_price (unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.unit_label_snapshot IS \'Ví dụ: Thùng 36 chai\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_provider_price.factor_to_base_snapshot IS 'Snapshot hệ số tại thời điểm tạo giá'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.price IS \'Giá gốc\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.discount_rate IS \'% giảm giá\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_provider_price.discount_amount IS 'Số tiền giảm trực tiếp'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.price_after_discount IS \'Giá sau giảm\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.currency IS \'VND\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.effective_from IS \'Ngày bắt đầu\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.effective_to IS \'Ngày kết thúc\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.is_default IS \'Giá mặc định\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.status IS \'Trạng thái giá\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise_provider_unit (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              factor_to_base NUMERIC(10, 4) NOT NULL,
              level INT DEFAULT 0 NOT NULL,
              label VARCHAR(255) DEFAULT NULL,
              is_base BOOLEAN DEFAULT false NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              merchandise_provider_id INT NOT NULL,
              unit_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_FD0C717880455FD2 ON merchandise_provider_unit (merchandise_provider_id)');
        $this->addSql('CREATE INDEX IDX_FD0C7178F8BD700D ON merchandise_provider_unit (unit_id)');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_provider_unit.factor_to_base IS 'Hệ số quy đổi ra base unit'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit.level IS \'Cấp độ đơn vị\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit.label IS \'Ví dụ: Thùng 16 chai, Lốc 4 chai\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit.is_base IS \'Có phải đơn vị gốc không\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise_provider_unit_conversion (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              from_value NUMERIC(10, 2) DEFAULT '1.00' NOT NULL,
              to_value NUMERIC(10, 2) NOT NULL,
              sort_order INT DEFAULT 0,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              merchandise_provider_id INT NOT NULL,
              from_unit_id INT NOT NULL,
              to_unit_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1EA78A380455FD2 ON merchandise_provider_unit_conversion (merchandise_provider_id)
        SQL);
        $this->addSql('CREATE INDEX IDX_1EA78A37EE393A2 ON merchandise_provider_unit_conversion (from_unit_id)');
        $this->addSql('CREATE INDEX IDX_1EA78A376254DF8 ON merchandise_provider_unit_conversion (to_unit_id)');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_provider_unit_conversion.from_value IS 'Giá trị quy đổi từ (thường là 1)'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_provider_unit_conversion.to_value IS 'Giá trị quy đổi sang'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit_conversion.sort_order IS \'Thứ tự sắp xếp\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise_recipe (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              output_quantity NUMERIC(10, 4) DEFAULT '1.0000' NOT NULL,
              output_factor_to_base_snapshot NUMERIC(10, 4) DEFAULT NULL,
              output_base_quantity_snapshot NUMERIC(10, 4) DEFAULT NULL,
              version INT DEFAULT 1 NOT NULL,
              is_active BOOLEAN DEFAULT true NOT NULL,
              status SMALLINT DEFAULT 1 NOT NULL,
              notes TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              finished_product_id INT NOT NULL,
              output_unit_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_703AF543380E9C02 ON merchandise_recipe (finished_product_id)');
        $this->addSql('CREATE INDEX IDX_703AF54321BFF7EB ON merchandise_recipe (output_unit_id)');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_recipe.output_quantity IS 'Định lượng thành phẩm đầu ra'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_recipe.output_factor_to_base_snapshot IS 'Factor quy đổi của đơn vị thành phẩm về base unit tại thời điểm lưu'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_recipe.output_base_quantity_snapshot IS 'Số lượng thành phẩm quy đổi về base unit tại thời điểm lưu'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.version IS \'Version công thức\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.is_active IS \'Trạng thái hoạt động\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.status IS \'Status\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.notes IS \'Ghi chú\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise_recipe_item (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              quantity NUMERIC(10, 4) NOT NULL,
              factor_to_base_snapshot NUMERIC(10, 4) DEFAULT NULL,
              base_quantity_snapshot NUMERIC(10, 4) DEFAULT NULL,
              waste_rate NUMERIC(5, 2) DEFAULT '0.00' NOT NULL,
              sort_order INT DEFAULT 0 NOT NULL,
              notes TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              recipe_id INT NOT NULL,
              ingredient_id INT NOT NULL,
              unit_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_EA1688B959D8A214 ON merchandise_recipe_item (recipe_id)');
        $this->addSql('CREATE INDEX IDX_EA1688B9933FE08C ON merchandise_recipe_item (ingredient_id)');
        $this->addSql('CREATE INDEX IDX_EA1688B9F8BD700D ON merchandise_recipe_item (unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.quantity IS \'Định lượng\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_recipe_item.factor_to_base_snapshot IS 'Tỉ lệ quy đổi về base unit của nguyên liệu tại thời điểm lưu'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_recipe_item.base_quantity_snapshot IS 'Số lượng quy đổi ra base unit của nguyên liệu tại thời điểm lưu'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.waste_rate IS \'Tỉ lệ hao hụt %\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.sort_order IS \'Thứ tự sắp xếp\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.notes IS \'Ghi chú\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise_unit (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              factor_to_base NUMERIC(10, 4) NOT NULL,
              level INT DEFAULT 0 NOT NULL,
              label VARCHAR(255) DEFAULT NULL,
              is_base BOOLEAN DEFAULT false NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              merchandise_id INT NOT NULL,
              unit_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_69356D64CFC6D428 ON merchandise_unit (merchandise_id)');
        $this->addSql('CREATE INDEX IDX_69356D64F8BD700D ON merchandise_unit (unit_id)');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_unit.factor_to_base IS 'Hệ số quy đổi ra base unit (1 đơn vị này = bao nhiêu base unit)'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise_unit.level IS \'base = 0, càng lớn càng là đơn vị lớn\'');
        $this->addSql('COMMENT ON COLUMN merchandise_unit.label IS \'Ví dụ: Thùng 36 chai\'');
        $this->addSql('COMMENT ON COLUMN merchandise_unit.is_base IS \'true nếu là base unit\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE merchandise_unit_conversion (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              from_value NUMERIC(10, 2) DEFAULT '1.00' NOT NULL,
              to_value NUMERIC(10, 2) NOT NULL,
              sort_order INT DEFAULT 0,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              merchandise_id INT NOT NULL,
              from_unit_id INT NOT NULL,
              to_unit_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B1CC834BCFC6D428 ON merchandise_unit_conversion (merchandise_id)');
        $this->addSql('CREATE INDEX IDX_B1CC834B7EE393A2 ON merchandise_unit_conversion (from_unit_id)');
        $this->addSql('CREATE INDEX IDX_B1CC834B76254DF8 ON merchandise_unit_conversion (to_unit_id)');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN merchandise_unit_conversion.from_value IS 'Đơn vị quy đổi từ (thường là 1)'
        SQL);
        $this->addSql('COMMENT ON COLUMN merchandise_unit_conversion.to_value IS \'Số lượng quy đổi sang\'');
        $this->addSql('COMMENT ON COLUMN merchandise_unit_conversion.sort_order IS \'Thứ tự hiển thị UI\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE message (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) DEFAULT NULL,
              content TEXT DEFAULT NULL,
              images JSON DEFAULT NULL,
              files JSON DEFAULT NULL,
              is_seen BOOLEAN DEFAULT false,
              seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              is_deleted BOOLEAN DEFAULT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              conversation_id INT DEFAULT NULL,
              sender_id INT DEFAULT NULL,
              receiver_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B6BD307F77153098 ON message (code)');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FCD53EDB6 ON message (receiver_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE notification (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) NOT NULL,
              from_id INT NOT NULL,
              to_id INT NOT NULL,
              title VARCHAR(255) NOT NULL,
              body TEXT NOT NULL,
              icon VARCHAR(255) NOT NULL,
              color VARCHAR(255) NOT NULL,
              seen BOOLEAN DEFAULT false NOT NULL,
              link VARCHAR(255) DEFAULT NULL,
              is_created BOOLEAN DEFAULT false NOT NULL,
              type_notification VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_notification_to_id ON notification (to_id)');
        $this->addSql('CREATE INDEX idx_notification_to_id_seen ON notification (to_id, seen)');
        $this->addSql(<<<'SQL'
            CREATE TABLE "position" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) DEFAULT NULL,
              name VARCHAR(255) DEFAULT NULL,
              description TEXT DEFAULT NULL,
              employment_type VARCHAR(255) DEFAULT 'FULL_TIME',
              min_salary NUMERIC(15, 2) DEFAULT NULL,
              max_salary NUMERIC(15, 2) DEFAULT NULL,
              currency VARCHAR(255) DEFAULT NULL,
              probation_months INT DEFAULT 2,
              probation_salary_rate INT DEFAULT 85,
              annual_leave_days INT DEFAULT 12,
              review_cycle_months INT DEFAULT 12,
              notice_period_days INT DEFAULT 12,
              allowances JSON DEFAULT NULL,
              status INT DEFAULT 1,
              is_manager INT DEFAULT 0,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              department_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_462CE4F5AE80F5DF ON "position" (department_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_CODE ON "position" (code) WHERE deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "position".employment_type IS \'Hinh thuc lam viec (FULL_TIME, PART_TIME...)\'');
        $this->addSql('COMMENT ON COLUMN "position".probation_months IS \'So thang thu viec tieu chuan\'');
        $this->addSql('COMMENT ON COLUMN "position".probation_salary_rate IS \'Ty le huong luong thu viec (%)\'');
        $this->addSql('COMMENT ON COLUMN "position".annual_leave_days IS \'So ngay nghi phep nam tieu chuan\'');
        $this->addSql('COMMENT ON COLUMN "position".review_cycle_months IS \'So thang danh gia luong nam tieu chuan\'');
        $this->addSql('COMMENT ON COLUMN "position".notice_period_days IS \'So ngay thong bao truoc khi nghi viec\'');
        $this->addSql('COMMENT ON COLUMN "position".allowances IS \'Danh sach phu cap (JSON)\'');
        $this->addSql('COMMENT ON COLUMN "position".status IS \'1: active, 0: inactive\'');
        $this->addSql('COMMENT ON COLUMN "position".is_manager IS \'1: yes, 0: no\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE provider (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) NOT NULL,
              name VARCHAR(255) NOT NULL,
              phone VARCHAR(255) DEFAULT NULL,
              email VARCHAR(255) DEFAULT NULL,
              address VARCHAR(255) DEFAULT NULL,
              tax_number VARCHAR(255) DEFAULT NULL,
              bank_name VARCHAR(255) DEFAULT NULL,
              bank_number VARCHAR(255) DEFAULT NULL,
              note TEXT DEFAULT NULL,
              status INT DEFAULT 1,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROVIDER_CODE ON provider (code) WHERE deleted_at IS NULL');
        $this->addSql(<<<'SQL'
            CREATE TABLE refresh_tokens (
              refresh_token VARCHAR(128) NOT NULL,
              username VARCHAR(255) NOT NULL,
              valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql(<<<'SQL'
            CREATE TABLE request (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(50) NOT NULL,
              type VARCHAR(50) NOT NULL,
              source VARCHAR(20) DEFAULT 'manual' NOT NULL,
              status VARCHAR(30) NOT NULL,
              requester_department_snapshot JSON DEFAULT NULL,
              requester_position_snapshot JSON DEFAULT NULL,
              current_step_no INT NOT NULL,
              revision_no INT NOT NULL,
              title VARCHAR(255) NOT NULL,
              summary TEXT DEFAULT NULL,
              payload JSON DEFAULT NULL,
              last_reject_reason TEXT DEFAULT NULL,
              source_ref_type VARCHAR(50) DEFAULT NULL,
              source_ref_id INT DEFAULT NULL,
              target_ref_type VARCHAR(50) DEFAULT NULL,
              target_ref_id INT DEFAULT NULL,
              submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              rejected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              requester_id INT NOT NULL,
              current_approver_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B978F9F77153098 ON request (code)');
        $this->addSql('CREATE INDEX IDX_3B978F9FED442CF4 ON request (requester_id)');
        $this->addSql('CREATE INDEX IDX_3B978F9F5F7DDB5 ON request (current_approver_id)');
        $this->addSql('CREATE INDEX idx_request_status ON request (status)');
        $this->addSql('CREATE INDEX idx_request_type ON request (type)');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.type IS 'Loại đề xuất, ví dụ: leave, purchase, resignation'
        SQL);
        $this->addSql('COMMENT ON COLUMN request.source IS \'Nguồn tạo đề xuất: manual hoặc system\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.status IS 'Trạng thái hiện tại của đề xuất: pending, rejected, approved, cancelled'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.requester_department_snapshot IS 'Snapshot JSON của bộ phận chính của người tạo tại thời điểm tạo đề xuất'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.requester_position_snapshot IS 'Snapshot JSON của chức vụ chính của người tạo tại thời điểm tạo đề xuất'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.current_step_no IS 'Bước duyệt hiện tại, có thể mở rộng duyệt nhiều cấp'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.revision_no IS 'Số lần gửi lại đề xuất sau khi bị từ chối'
        SQL);
        $this->addSql('COMMENT ON COLUMN request.title IS \'Tiêu đề của đề xuất\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.summary IS 'Mô tả tóm tắt của đề xuất để hiển thị ở danh sách'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.payload IS 'Payload JSON chứa dữ liệu chi tiết riêng theo từng loại đề xuất'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.last_reject_reason IS 'Lý do từ chối gần nhất của đề xuất'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.source_ref_type IS 'Loại bản ghi nguồn đã tự động sinh ra đề xuất'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.source_ref_id IS 'ID bản ghi nguồn đã tự động sinh ra đề xuất'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.target_ref_type IS 'Loại dữ liệu đích được tạo hoặc cập nhật sau khi duyệt'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.target_ref_id IS 'ID dữ liệu đích được tạo hoặc cập nhật sau khi duyệt'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.submitted_at IS 'Thời điểm đề xuất được gửi đi để chờ duyệt'
        SQL);
        $this->addSql('COMMENT ON COLUMN request.approved_at IS \'Thời điểm đề xuất được duyệt\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.rejected_at IS 'Thời điểm đề xuất bị từ chối gần nhất'
        SQL);
        $this->addSql('COMMENT ON COLUMN request.cancelled_at IS \'Thời điểm đề xuất bị hủy\'');
        $this->addSql('COMMENT ON COLUMN request.requester_id IS \'Người tạo đề xuất\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request.current_approver_id IS 'Người duyệt hiện tại của đề xuất'
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE request_approval_step (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              step_no INT NOT NULL,
              revision_no INT NOT NULL,
              status VARCHAR(30) NOT NULL,
              decision_comment TEXT DEFAULT NULL,
              acted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              request_id INT NOT NULL,
              approver_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_1F7A946C427EB8A5 ON request_approval_step (request_id)');
        $this->addSql('CREATE INDEX IDX_1F7A946CBB23766C ON request_approval_step (approver_id)');
        $this->addSql('COMMENT ON COLUMN request_approval_step.step_no IS \'Số thứ tự bước duyệt\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_approval_step.revision_no IS 'Lần gửi đề xuất mà bước duyệt này tương ứng'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_approval_step.status IS 'Trạng thái của bước duyệt: pending, approved, rejected, cancelled'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_approval_step.decision_comment IS 'Ghi chú hoặc lý do xử lý của người duyệt'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_approval_step.acted_at IS 'Thời điểm người duyệt thực hiện hành động ở bước này'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_approval_step.approver_id IS 'Người chịu trách nhiệm duyệt ở bước này'
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE request_event (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              event_type VARCHAR(50) NOT NULL,
              actor_type VARCHAR(20) DEFAULT 'user' NOT NULL,
              step_no INT DEFAULT NULL,
              revision_no INT DEFAULT NULL,
              from_status VARCHAR(30) DEFAULT NULL,
              to_status VARCHAR(30) DEFAULT NULL,
              comment TEXT DEFAULT NULL,
              payload_snapshot JSON DEFAULT NULL,
              meta JSON DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              request_id INT NOT NULL,
              actor_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_66B9B682427EB8A5 ON request_event (request_id)');
        $this->addSql('CREATE INDEX IDX_66B9B68210DAF24A ON request_event (actor_id)');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_event.event_type IS 'Loại sự kiện timeline: created, submitted, approved, rejected...'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_event.actor_type IS 'Loại actor tạo ra sự kiện: user, system, job'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_event.step_no IS 'Bước duyệt liên quan đến sự kiện này'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_event.revision_no IS 'Lần gửi đề xuất liên quan đến sự kiện này'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_event.from_status IS 'Trạng thái trước khi sự kiện xảy ra'
        SQL);
        $this->addSql('COMMENT ON COLUMN request_event.to_status IS \'Trạng thái sau khi sự kiện xảy ra\'');
        $this->addSql('COMMENT ON COLUMN request_event.comment IS \'Nội dung ghi chú đi kèm sự kiện timeline\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_event.payload_snapshot IS 'Snapshot payload của đề xuất tại thời điểm sự kiện diễn ra'
        SQL);
        $this->addSql('COMMENT ON COLUMN request_event.meta IS \'Metadata mở rộng của sự kiện timeline\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_event.created_at IS 'Thời điểm sự kiện timeline được ghi nhận'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_event.actor_id IS 'Người thực hiện hành động tạo ra sự kiện timeline này'
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE request_watcher (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              watch_type VARCHAR(20) DEFAULT 'viewer',
              notify_on_submit BOOLEAN DEFAULT true NOT NULL,
              notify_on_reject BOOLEAN DEFAULT true NOT NULL,
              notify_on_approve BOOLEAN DEFAULT true NOT NULL,
              notify_on_comment BOOLEAN DEFAULT true NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              request_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_98AB94FB427EB8A5 ON request_watcher (request_id)');
        $this->addSql('CREATE INDEX IDX_98AB94FBA76ED395 ON request_watcher (user_id)');
        $this->addSql('COMMENT ON COLUMN request_watcher.watch_type IS \'Loại theo dõi: viewer, cc, observer...\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_watcher.notify_on_submit IS 'Có nhận thông báo khi đề xuất được gửi đi hay không'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_watcher.notify_on_reject IS 'Có nhận thông báo khi đề xuất bị từ chối hay không'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_watcher.notify_on_approve IS 'Có nhận thông báo khi đề xuất được duyệt hay không'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_watcher.notify_on_comment IS 'Có nhận thông báo khi có trao đổi hoặc comment hay không'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN request_watcher.created_at IS 'Thời điểm người theo dõi được thêm vào đề xuất'
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE shift_assignment (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              work_date DATE DEFAULT NULL,
              start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              member_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_47A0F957597D3FE ON shift_assignment (member_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE unit (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) NOT NULL,
              name VARCHAR(255) NOT NULL,
              symbol VARCHAR(255) DEFAULT NULL,
              status INT DEFAULT 1,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_UNIT_CODE ON unit (code) WHERE deleted_at IS NULL');
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              roles JSON DEFAULT NULL,
              password VARCHAR(255) NOT NULL,
              name VARCHAR(255) NOT NULL,
              phone VARCHAR(20) DEFAULT NULL,
              gender VARCHAR(255) DEFAULT NULL,
              province VARCHAR(255) DEFAULT NULL,
              district VARCHAR(255) DEFAULT NULL,
              ward VARCHAR(255) DEFAULT NULL,
              address VARCHAR(255) DEFAULT NULL,
              birthday VARCHAR(255) DEFAULT NULL,
              image VARCHAR(255) DEFAULT NULL,
              description VARCHAR(255) DEFAULT NULL,
              email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              status INT DEFAULT 1 NOT NULL,
              is_ngoai_gio INT DEFAULT 0 NOT NULL,
              hinh_thuc_lam_viec VARCHAR(255) DEFAULT NULL,
              ma_nhan_vien VARCHAR(50) DEFAULT NULL,
              cmnd VARCHAR(20) DEFAULT NULL,
              ngay_cap_cmnd VARCHAR(20) DEFAULT NULL,
              noi_cap_cmnd VARCHAR(255) DEFAULT NULL,
              ngay_vao_lam VARCHAR(20) DEFAULT NULL,
              remember_token VARCHAR(100) DEFAULT NULL,
              is_first_login INT DEFAULT 1 NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_MA_NHAN_VIEN ON "user" (ma_nhan_vien) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_PHONE ON "user" (phone) WHERE deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".status IS \'1: active, 0: inactive\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN "user".is_ngoai_gio IS '0: cho phép ngoài giờ, 1: không cho phép ngoài giờ'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN "user".is_first_login IS '0: tài khoản đã đổi mật khẩu, 1: tài khoản đăng nhập lần đầu tiên'
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_has_custom_permission (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              module JSON DEFAULT NULL,
              user_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2228D2C3A76ED395 ON user_has_custom_permission (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE user_permission (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              user_id INT NOT NULL,
              department_id INT NOT NULL,
              position_id INT NOT NULL,
              phan_quyen JSON DEFAULT NULL,
              start_temp INT DEFAULT NULL,
              end_temp INT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_position (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              salary NUMERIC(10, 2) DEFAULT NULL,
              allowances JSON DEFAULT NULL,
              allowances_total JSON DEFAULT NULL,
              effective_from DATE DEFAULT NULL,
              effective_to DATE DEFAULT NULL,
              probation_from DATE DEFAULT NULL,
              probation_to DATE DEFAULT NULL,
              salary_net NUMERIC(15, 2) DEFAULT NULL,
              salary_gross NUMERIC(15, 2) DEFAULT NULL,
              insurance_salary NUMERIC(15, 2) DEFAULT NULL,
              insurance_code VARCHAR(255) DEFAULT NULL,
              note TEXT DEFAULT NULL,
              position_snapshot JSON DEFAULT NULL,
              status INT DEFAULT 1,
              is_primary INT DEFAULT 0,
              contracts JSON DEFAULT NULL,
              start_temp INT DEFAULT NULL,
              end_temp INT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              department_id INT DEFAULT NULL,
              position_id INT DEFAULT NULL,
              member_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_A6A100F5AE80F5DF ON user_position (department_id)');
        $this->addSql('CREATE INDEX IDX_A6A100F5DD842E46 ON user_position (position_id)');
        $this->addSql('CREATE INDEX IDX_A6A100F57597D3FE ON user_position (member_id)');
        $this->addSql('COMMENT ON COLUMN user_position.status IS \'1: active, 0: inactive\'');
        $this->addSql('COMMENT ON COLUMN user_position.is_primary IS \'1: yes, 0: no\'');
        $this->addSql(<<<'SQL'
            CREATE TABLE user_signature (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              signature_png_path VARCHAR(255) NOT NULL,
              signature_svg_path VARCHAR(255) NOT NULL,
              signature_strokes JSON DEFAULT NULL,
              width INT DEFAULT NULL,
              height INT DEFAULT NULL,
              file_size INT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AE688CA5A76ED395 ON user_signature (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE warehouse (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) DEFAULT NULL,
              name VARCHAR(255) DEFAULT NULL,
              type VARCHAR(255) DEFAULT NULL,
              status BOOLEAN DEFAULT true,
              note TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              branch_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ECB38BFCDCD6CC49 ON warehouse (branch_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WAREHOUSE_CODE ON warehouse (code) WHERE deleted_at IS NULL');
        $this->addSql(<<<'SQL'
            CREATE TABLE work_shift (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              gio_bat_dau VARCHAR(255) NOT NULL,
              gio_ket_thuc VARCHAR(255) NOT NULL,
              ghi_chu VARCHAR(255) NOT NULL,
              color VARCHAR(255) DEFAULT NULL,
              status BOOLEAN DEFAULT true NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              thoi_gian_lam_viec_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_8DF0406A2DBE3FA2 ON work_shift (thoi_gian_lam_viec_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE work_shift_assignment (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              note TEXT DEFAULT NULL,
              date DATE DEFAULT NULL,
              work_shift_id INT DEFAULT NULL,
              member_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_21872E4F6EC53652 ON work_shift_assignment (work_shift_id)');
        $this->addSql('CREATE INDEX IDX_21872E4F7597D3FE ON work_shift_assignment (member_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE working_time (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              thu VARCHAR(255) NOT NULL,
              day_of_week INT DEFAULT NULL,
              gio_bat_dau VARCHAR(255) DEFAULT NULL,
              gio_ket_thuc VARCHAR(255) DEFAULT NULL,
              ghi_chu VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_by INT DEFAULT NULL,
              updated_by INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              body TEXT NOT NULL,
              headers TEXT NOT NULL,
              queue_name VARCHAR(190) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (
              queue_name, available_at, delivered_at,
              id
            )
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              attendance
            ADD
              CONSTRAINT FK_6DE30D918C03F15C FOREIGN KEY (employee_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              attendance
            ADD
              CONSTRAINT FK_6DE30D91655C1043 FOREIGN KEY (work_shift_assignment_id) REFERENCES work_shift_assignment (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              attendance_log
            ADD
              CONSTRAINT FK_8920D967163DDA15 FOREIGN KEY (attendance_id) REFERENCES attendance (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              category
            ADD
              CONSTRAINT FK_64C19C1727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              conversation
            ADD
              CONSTRAINT FK_8A8E26E9D7208CD7 FOREIGN KEY (bo_phan_id) REFERENCES department (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              conversation_user
            ADD
              CONSTRAINT FK_5AECB5559AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              conversation_user
            ADD
              CONSTRAINT FK_5AECB555A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              fixed_schedule
            ADD
              CONSTRAINT FK_65FA44A116AB3DE1 FOREIGN KEY (fixed_schedule_group_id) REFERENCES fixed_schedule_group (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              fixed_schedule_group
            ADD
              CONSTRAINT FK_3F0C6B937597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              fixed_schedule_override
            ADD
              CONSTRAINT FK_6AFCE2437597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              folder
            ADD
              CONSTRAINT FK_ECA209CD727ACA70 FOREIGN KEY (parent_id) REFERENCES folder (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              folder
            ADD
              CONSTRAINT FK_ECA209CD7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              leave_schedule
            ADD
              CONSTRAINT FK_641039587597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              media
            ADD
              CONSTRAINT FK_6A2CA10C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              media
            ADD
              CONSTRAINT FK_6A2CA10C162CB942 FOREIGN KEY (folder_id) REFERENCES folder (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise
            ADD
              CONSTRAINT FK_D043D1A412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise
            ADD
              CONSTRAINT FK_D043D1A4CCBBC969 FOREIGN KEY (base_unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider
            ADD
              CONSTRAINT FK_A826E055CFC6D428 FOREIGN KEY (merchandise_id) REFERENCES merchandise (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider
            ADD
              CONSTRAINT FK_A826E055A53A8AA FOREIGN KEY (provider_id) REFERENCES provider (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider_price
            ADD
              CONSTRAINT FK_66556CE480455FD2 FOREIGN KEY (merchandise_provider_id) REFERENCES merchandise_provider (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider_price
            ADD
              CONSTRAINT FK_66556CE4F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider_unit
            ADD
              CONSTRAINT FK_FD0C717880455FD2 FOREIGN KEY (merchandise_provider_id) REFERENCES merchandise_provider (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider_unit
            ADD
              CONSTRAINT FK_FD0C7178F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider_unit_conversion
            ADD
              CONSTRAINT FK_1EA78A380455FD2 FOREIGN KEY (merchandise_provider_id) REFERENCES merchandise_provider (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider_unit_conversion
            ADD
              CONSTRAINT FK_1EA78A37EE393A2 FOREIGN KEY (from_unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_provider_unit_conversion
            ADD
              CONSTRAINT FK_1EA78A376254DF8 FOREIGN KEY (to_unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_recipe
            ADD
              CONSTRAINT FK_703AF543380E9C02 FOREIGN KEY (finished_product_id) REFERENCES merchandise (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_recipe
            ADD
              CONSTRAINT FK_703AF54321BFF7EB FOREIGN KEY (output_unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_recipe_item
            ADD
              CONSTRAINT FK_EA1688B959D8A214 FOREIGN KEY (recipe_id) REFERENCES merchandise_recipe (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_recipe_item
            ADD
              CONSTRAINT FK_EA1688B9933FE08C FOREIGN KEY (ingredient_id) REFERENCES merchandise (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_recipe_item
            ADD
              CONSTRAINT FK_EA1688B9F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_unit
            ADD
              CONSTRAINT FK_69356D64CFC6D428 FOREIGN KEY (merchandise_id) REFERENCES merchandise (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_unit
            ADD
              CONSTRAINT FK_69356D64F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_unit_conversion
            ADD
              CONSTRAINT FK_B1CC834BCFC6D428 FOREIGN KEY (merchandise_id) REFERENCES merchandise (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_unit_conversion
            ADD
              CONSTRAINT FK_B1CC834B7EE393A2 FOREIGN KEY (from_unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              merchandise_unit_conversion
            ADD
              CONSTRAINT FK_B1CC834B76254DF8 FOREIGN KEY (to_unit_id) REFERENCES unit (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              message
            ADD
              CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              message
            ADD
              CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              message
            ADD
              CONSTRAINT FK_B6BD307FCD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              "position"
            ADD
              CONSTRAINT FK_462CE4F5AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              request
            ADD
              CONSTRAINT FK_3B978F9FED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              request
            ADD
              CONSTRAINT FK_3B978F9F5F7DDB5 FOREIGN KEY (current_approver_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              request_approval_step
            ADD
              CONSTRAINT FK_1F7A946C427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              request_approval_step
            ADD
              CONSTRAINT FK_1F7A946CBB23766C FOREIGN KEY (approver_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              request_event
            ADD
              CONSTRAINT FK_66B9B682427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              request_event
            ADD
              CONSTRAINT FK_66B9B68210DAF24A FOREIGN KEY (actor_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              request_watcher
            ADD
              CONSTRAINT FK_98AB94FB427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              request_watcher
            ADD
              CONSTRAINT FK_98AB94FBA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              shift_assignment
            ADD
              CONSTRAINT FK_47A0F957597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_has_custom_permission
            ADD
              CONSTRAINT FK_2228D2C3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_position
            ADD
              CONSTRAINT FK_A6A100F5AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_position
            ADD
              CONSTRAINT FK_A6A100F5DD842E46 FOREIGN KEY (position_id) REFERENCES "position" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_position
            ADD
              CONSTRAINT FK_A6A100F57597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_signature
            ADD
              CONSTRAINT FK_AE688CA5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              warehouse
            ADD
              CONSTRAINT FK_ECB38BFCDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              work_shift
            ADD
              CONSTRAINT FK_8DF0406A2DBE3FA2 FOREIGN KEY (thoi_gian_lam_viec_id) REFERENCES working_time (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              work_shift_assignment
            ADD
              CONSTRAINT FK_21872E4F6EC53652 FOREIGN KEY (work_shift_id) REFERENCES work_shift (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              work_shift_assignment
            ADD
              CONSTRAINT FK_21872E4F7597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D918C03F15C');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D91655C1043');
        $this->addSql('ALTER TABLE attendance_log DROP CONSTRAINT FK_8920D967163DDA15');
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1727ACA70');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9D7208CD7');
        $this->addSql('ALTER TABLE conversation_user DROP CONSTRAINT FK_5AECB5559AC0396');
        $this->addSql('ALTER TABLE conversation_user DROP CONSTRAINT FK_5AECB555A76ED395');
        $this->addSql('ALTER TABLE fixed_schedule DROP CONSTRAINT FK_65FA44A116AB3DE1');
        $this->addSql('ALTER TABLE fixed_schedule_group DROP CONSTRAINT FK_3F0C6B937597D3FE');
        $this->addSql('ALTER TABLE fixed_schedule_override DROP CONSTRAINT FK_6AFCE2437597D3FE');
        $this->addSql('ALTER TABLE folder DROP CONSTRAINT FK_ECA209CD727ACA70');
        $this->addSql('ALTER TABLE folder DROP CONSTRAINT FK_ECA209CD7E3C61F9');
        $this->addSql('ALTER TABLE leave_schedule DROP CONSTRAINT FK_641039587597D3FE');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C7E3C61F9');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C162CB942');
        $this->addSql('ALTER TABLE merchandise DROP CONSTRAINT FK_D043D1A412469DE2');
        $this->addSql('ALTER TABLE merchandise DROP CONSTRAINT FK_D043D1A4CCBBC969');
        $this->addSql('ALTER TABLE merchandise_provider DROP CONSTRAINT FK_A826E055CFC6D428');
        $this->addSql('ALTER TABLE merchandise_provider DROP CONSTRAINT FK_A826E055A53A8AA');
        $this->addSql('ALTER TABLE merchandise_provider_price DROP CONSTRAINT FK_66556CE480455FD2');
        $this->addSql('ALTER TABLE merchandise_provider_price DROP CONSTRAINT FK_66556CE4F8BD700D');
        $this->addSql('ALTER TABLE merchandise_provider_unit DROP CONSTRAINT FK_FD0C717880455FD2');
        $this->addSql('ALTER TABLE merchandise_provider_unit DROP CONSTRAINT FK_FD0C7178F8BD700D');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion DROP CONSTRAINT FK_1EA78A380455FD2');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion DROP CONSTRAINT FK_1EA78A37EE393A2');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion DROP CONSTRAINT FK_1EA78A376254DF8');
        $this->addSql('ALTER TABLE merchandise_recipe DROP CONSTRAINT FK_703AF543380E9C02');
        $this->addSql('ALTER TABLE merchandise_recipe DROP CONSTRAINT FK_703AF54321BFF7EB');
        $this->addSql('ALTER TABLE merchandise_recipe_item DROP CONSTRAINT FK_EA1688B959D8A214');
        $this->addSql('ALTER TABLE merchandise_recipe_item DROP CONSTRAINT FK_EA1688B9933FE08C');
        $this->addSql('ALTER TABLE merchandise_recipe_item DROP CONSTRAINT FK_EA1688B9F8BD700D');
        $this->addSql('ALTER TABLE merchandise_unit DROP CONSTRAINT FK_69356D64CFC6D428');
        $this->addSql('ALTER TABLE merchandise_unit DROP CONSTRAINT FK_69356D64F8BD700D');
        $this->addSql('ALTER TABLE merchandise_unit_conversion DROP CONSTRAINT FK_B1CC834BCFC6D428');
        $this->addSql('ALTER TABLE merchandise_unit_conversion DROP CONSTRAINT FK_B1CC834B7EE393A2');
        $this->addSql('ALTER TABLE merchandise_unit_conversion DROP CONSTRAINT FK_B1CC834B76254DF8');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FCD53EDB6');
        $this->addSql('ALTER TABLE "position" DROP CONSTRAINT FK_462CE4F5AE80F5DF');
        $this->addSql('ALTER TABLE request DROP CONSTRAINT FK_3B978F9FED442CF4');
        $this->addSql('ALTER TABLE request DROP CONSTRAINT FK_3B978F9F5F7DDB5');
        $this->addSql('ALTER TABLE request_approval_step DROP CONSTRAINT FK_1F7A946C427EB8A5');
        $this->addSql('ALTER TABLE request_approval_step DROP CONSTRAINT FK_1F7A946CBB23766C');
        $this->addSql('ALTER TABLE request_event DROP CONSTRAINT FK_66B9B682427EB8A5');
        $this->addSql('ALTER TABLE request_event DROP CONSTRAINT FK_66B9B68210DAF24A');
        $this->addSql('ALTER TABLE request_watcher DROP CONSTRAINT FK_98AB94FB427EB8A5');
        $this->addSql('ALTER TABLE request_watcher DROP CONSTRAINT FK_98AB94FBA76ED395');
        $this->addSql('ALTER TABLE shift_assignment DROP CONSTRAINT FK_47A0F957597D3FE');
        $this->addSql('ALTER TABLE user_has_custom_permission DROP CONSTRAINT FK_2228D2C3A76ED395');
        $this->addSql('ALTER TABLE user_position DROP CONSTRAINT FK_A6A100F5AE80F5DF');
        $this->addSql('ALTER TABLE user_position DROP CONSTRAINT FK_A6A100F5DD842E46');
        $this->addSql('ALTER TABLE user_position DROP CONSTRAINT FK_A6A100F57597D3FE');
        $this->addSql('ALTER TABLE user_signature DROP CONSTRAINT FK_AE688CA5A76ED395');
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT FK_ECB38BFCDCD6CC49');
        $this->addSql('ALTER TABLE work_shift DROP CONSTRAINT FK_8DF0406A2DBE3FA2');
        $this->addSql('ALTER TABLE work_shift_assignment DROP CONSTRAINT FK_21872E4F6EC53652');
        $this->addSql('ALTER TABLE work_shift_assignment DROP CONSTRAINT FK_21872E4F7597D3FE');
        $this->addSql('DROP TABLE attendance');
        $this->addSql('DROP TABLE attendance_log');
        $this->addSql('DROP TABLE branch');
        $this->addSql('DROP TABLE cache_persist');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE conversation_user');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE fixed_schedule');
        $this->addSql('DROP TABLE fixed_schedule_group');
        $this->addSql('DROP TABLE fixed_schedule_override');
        $this->addSql('DROP TABLE folder');
        $this->addSql('DROP TABLE general_setting');
        $this->addSql('DROP TABLE holiday_schedule');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE import_log');
        $this->addSql('DROP TABLE keep_alive_db');
        $this->addSql('DROP TABLE leave_schedule');
        $this->addSql('DROP TABLE login_device');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE merchandise');
        $this->addSql('DROP TABLE merchandise_provider');
        $this->addSql('DROP TABLE merchandise_provider_price');
        $this->addSql('DROP TABLE merchandise_provider_unit');
        $this->addSql('DROP TABLE merchandise_provider_unit_conversion');
        $this->addSql('DROP TABLE merchandise_recipe');
        $this->addSql('DROP TABLE merchandise_recipe_item');
        $this->addSql('DROP TABLE merchandise_unit');
        $this->addSql('DROP TABLE merchandise_unit_conversion');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE "position"');
        $this->addSql('DROP TABLE provider');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE request');
        $this->addSql('DROP TABLE request_approval_step');
        $this->addSql('DROP TABLE request_event');
        $this->addSql('DROP TABLE request_watcher');
        $this->addSql('DROP TABLE shift_assignment');
        $this->addSql('DROP TABLE unit');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_has_custom_permission');
        $this->addSql('DROP TABLE user_permission');
        $this->addSql('DROP TABLE user_position');
        $this->addSql('DROP TABLE user_signature');
        $this->addSql('DROP TABLE warehouse');
        $this->addSql('DROP TABLE work_shift');
        $this->addSql('DROP TABLE work_shift_assignment');
        $this->addSql('DROP TABLE working_time');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
