<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260703065315 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE merchandise_recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, output_quantity NUMERIC(10, 4) DEFAULT \'1.0000\' NOT NULL, output_factor_to_base_snapshot NUMERIC(10, 4) DEFAULT NULL, output_base_quantity_snapshot NUMERIC(10, 4) DEFAULT NULL, version INT DEFAULT 1 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, status SMALLINT DEFAULT 1 NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, finished_product_id INT NOT NULL, output_unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_703AF543380E9C02 ON merchandise_recipe (finished_product_id)');
        $this->addSql('CREATE INDEX IDX_703AF54321BFF7EB ON merchandise_recipe (output_unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.output_quantity IS \'Định lượng thành phẩm đầu ra\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.output_factor_to_base_snapshot IS \'Factor quy đổi của đơn vị thành phẩm về base unit tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.output_base_quantity_snapshot IS \'Số lượng thành phẩm quy đổi về base unit tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.version IS \'Version công thức\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.is_active IS \'Trạng thái hoạt động\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.status IS \'Status\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe.notes IS \'Ghi chú\'');
        $this->addSql('CREATE TABLE merchandise_recipe_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(10, 4) NOT NULL, factor_to_base_snapshot NUMERIC(10, 4) DEFAULT NULL, base_quantity_snapshot NUMERIC(10, 4) DEFAULT NULL, waste_rate NUMERIC(5, 2) DEFAULT \'0.00\' NOT NULL, sort_order INT DEFAULT 0 NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, recipe_id INT NOT NULL, ingredient_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA1688B959D8A214 ON merchandise_recipe_item (recipe_id)');
        $this->addSql('CREATE INDEX IDX_EA1688B9933FE08C ON merchandise_recipe_item (ingredient_id)');
        $this->addSql('CREATE INDEX IDX_EA1688B9F8BD700D ON merchandise_recipe_item (unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.quantity IS \'Định lượng\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.factor_to_base_snapshot IS \'Tỉ lệ quy đổi về base unit của nguyên liệu tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.base_quantity_snapshot IS \'Số lượng quy đổi ra base unit của nguyên liệu tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.waste_rate IS \'Tỉ lệ hao hụt %\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.sort_order IS \'Thứ tự sắp xếp\'');
        $this->addSql('COMMENT ON COLUMN merchandise_recipe_item.notes IS \'Ghi chú\'');
        $this->addSql('ALTER TABLE merchandise_recipe ADD CONSTRAINT FK_703AF543380E9C02 FOREIGN KEY (finished_product_id) REFERENCES merchandise (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_recipe ADD CONSTRAINT FK_703AF54321BFF7EB FOREIGN KEY (output_unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_recipe_item ADD CONSTRAINT FK_EA1688B959D8A214 FOREIGN KEY (recipe_id) REFERENCES merchandise_recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_recipe_item ADD CONSTRAINT FK_EA1688B9933FE08C FOREIGN KEY (ingredient_id) REFERENCES merchandise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_recipe_item ADD CONSTRAINT FK_EA1688B9F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_branch_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BRANCH_CODE ON branch (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_category_slug');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORY_SLUG ON category (slug) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_department_ma_bo_phan');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DEPARTMENT_MA_BO_PHAN ON department (ma_bo_phan) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_merchandise_code');
        $this->addSql('ALTER TABLE merchandise ADD finished_product_source VARCHAR(50) DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN merchandise.finished_product_source IS \'Nguồn thành phẩm (supplier, production)\'');
        $this->addSql('CREATE INDEX idx_merchandise_finished_product_source ON merchandise (finished_product_source)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MERCHANDISE_CODE ON merchandise (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_position_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_CODE ON "position" (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_provider_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROVIDER_CODE ON provider (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_unit_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_UNIT_CODE ON unit (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('DROP INDEX uniq_user_ma_nhan_vien');
        $this->addSql('DROP INDEX uniq_user_phone');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_MA_NHAN_VIEN ON "user" (ma_nhan_vien) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_PHONE ON "user" (phone) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_warehouse_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WAREHOUSE_CODE ON warehouse (code) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE merchandise_recipe DROP CONSTRAINT FK_703AF543380E9C02');
        $this->addSql('ALTER TABLE merchandise_recipe DROP CONSTRAINT FK_703AF54321BFF7EB');
        $this->addSql('ALTER TABLE merchandise_recipe_item DROP CONSTRAINT FK_EA1688B959D8A214');
        $this->addSql('ALTER TABLE merchandise_recipe_item DROP CONSTRAINT FK_EA1688B9933FE08C');
        $this->addSql('ALTER TABLE merchandise_recipe_item DROP CONSTRAINT FK_EA1688B9F8BD700D');
        $this->addSql('DROP TABLE merchandise_recipe');
        $this->addSql('DROP TABLE merchandise_recipe_item');
        $this->addSql('DROP INDEX UNIQ_BRANCH_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_branch_code ON branch (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_CATEGORY_SLUG');
        $this->addSql('CREATE UNIQUE INDEX uniq_category_slug ON category (slug) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_DEPARTMENT_MA_BO_PHAN');
        $this->addSql('CREATE UNIQUE INDEX uniq_department_ma_bo_phan ON department (ma_bo_phan) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_MERCHANDISE_CODE');
        $this->addSql('DROP INDEX idx_merchandise_finished_product_source');
        $this->addSql('ALTER TABLE merchandise DROP finished_product_source');
        $this->addSql('CREATE UNIQUE INDEX uniq_merchandise_code ON merchandise (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_POSITION_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_code ON "position" (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_PROVIDER_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_provider_code ON provider (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_UNIT_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_unit_code ON unit (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('DROP INDEX UNIQ_USER_MA_NHAN_VIEN');
        $this->addSql('DROP INDEX UNIQ_USER_PHONE');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_ma_nhan_vien ON "user" (ma_nhan_vien) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_phone ON "user" (phone) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_WAREHOUSE_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_warehouse_code ON warehouse (code) WHERE (deleted_at IS NULL)');
    }
}
