<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603134650 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attendance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, attendance_type VARCHAR(255) DEFAULT NULL, work_date DATE DEFAULT NULL, time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, validation_status VARCHAR(255) DEFAULT NULL, work_type VARCHAR(255) DEFAULT NULL, config_snapshot JSON DEFAULT NULL, work_schedule_snapshot JSON DEFAULT NULL, photo_path VARCHAR(255) DEFAULT NULL, late_minute INT DEFAULT NULL, early_leave_minute INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, employee_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6DE30D918C03F15C ON attendance (employee_id)');
        $this->addSql('COMMENT ON COLUMN attendance.attendance_type IS \'check_in/check_out\'');
        $this->addSql('COMMENT ON COLUMN attendance.status IS \'on_time,late,early_leave\'');
        $this->addSql('COMMENT ON COLUMN attendance.validation_status IS \'invalid/valid\'');
        $this->addSql('CREATE TABLE attendance_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, validation_status VARCHAR(255) DEFAULT NULL, validation_reason VARCHAR(255) DEFAULT NULL, ip_address VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longtitude VARCHAR(255) DEFAULT NULL, gps_accuracy_meter INT DEFAULT NULL, device_id INT DEFAULT NULL, qr_token VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, attendance_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8920D967163DDA15 ON attendance_log (attendance_id)');
        $this->addSql('COMMENT ON COLUMN attendance_log.validation_status IS \'invalid/valid\'');
        $this->addSql('COMMENT ON COLUMN attendance_log.validation_reason IS \'lưu code của reason\'');
        $this->addSql('COMMENT ON COLUMN attendance_log.latitude IS \'vĩ độ\'');
        $this->addSql('COMMENT ON COLUMN attendance_log.longtitude IS \'kinh độ\'');
        $this->addSql('COMMENT ON COLUMN attendance_log.gps_accuracy_meter IS \'khoảng cách\'');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D918C03F15C FOREIGN KEY (employee_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE attendance_log ADD CONSTRAINT FK_8920D967163DDA15 FOREIGN KEY (attendance_id) REFERENCES attendance (id)');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D918C03F15C');
        $this->addSql('ALTER TABLE attendance_log DROP CONSTRAINT FK_8920D967163DDA15');
        $this->addSql('DROP TABLE attendance');
        $this->addSql('DROP TABLE attendance_log');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
    }
}
