<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260329083138 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, salary NUMERIC(10, 2) DEFAULT NULL, allowances JSON DEFAULT NULL, effective_from DATE DEFAULT NULL, effective_to DATE DEFAULT NULL, probation_from DATE NOT NULL, probation_to DATE DEFAULT NULL, salary_net NUMERIC(15, 2) DEFAULT NULL, salary_gross NUMERIC(15, 2) DEFAULT NULL, insurance_salary NUMERIC(15, 2) DEFAULT NULL, insurance_code VARCHAR(255) DEFAULT NULL, note TEXT DEFAULT NULL, position_snapshot JSON DEFAULT NULL, contracts JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, department_id INT DEFAULT NULL, position_id INT DEFAULT NULL, member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A6A100F5AE80F5DF ON user_position (department_id)');
        $this->addSql('CREATE INDEX IDX_A6A100F5DD842E46 ON user_position (position_id)');
        $this->addSql('CREATE INDEX IDX_A6A100F57597D3FE ON user_position (member_id)');
        $this->addSql('ALTER TABLE user_position ADD CONSTRAINT FK_A6A100F5AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id)');
        $this->addSql('ALTER TABLE user_position ADD CONSTRAINT FK_A6A100F5DD842E46 FOREIGN KEY (position_id) REFERENCES position (id)');
        $this->addSql('ALTER TABLE user_position ADD CONSTRAINT FK_A6A100F57597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_position DROP CONSTRAINT FK_A6A100F5AE80F5DF');
        $this->addSql('ALTER TABLE user_position DROP CONSTRAINT FK_A6A100F5DD842E46');
        $this->addSql('ALTER TABLE user_position DROP CONSTRAINT FK_A6A100F57597D3FE');
        $this->addSql('DROP TABLE user_position');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
    }
}
