<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260523101741 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, source VARCHAR(20) DEFAULT \'manual\' NOT NULL, status VARCHAR(30) NOT NULL, requester_department_snapshot JSON DEFAULT NULL, requester_position_snapshot JSON DEFAULT NULL, current_step_no INT NOT NULL, revision_no INT NOT NULL, title VARCHAR(255) NOT NULL, summary TEXT DEFAULT NULL, payload JSON DEFAULT NULL, last_reject_reason TEXT DEFAULT NULL, source_ref_type VARCHAR(50) DEFAULT NULL, source_ref_id INT DEFAULT NULL, target_ref_type VARCHAR(50) DEFAULT NULL, target_ref_id INT DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rejected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, requester_id INT NOT NULL, current_approver_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B978F9F77153098 ON request (code)');
        $this->addSql('CREATE INDEX IDX_3B978F9FED442CF4 ON request (requester_id)');
        $this->addSql('CREATE INDEX IDX_3B978F9F5F7DDB5 ON request (current_approver_id)');
        $this->addSql('COMMENT ON COLUMN request.type IS \'Loại đề xuất, ví dụ: leave, purchase, resignation\'');
        $this->addSql('COMMENT ON COLUMN request.source IS \'Nguồn tạo đề xuất: manual hoặc system\'');
        $this->addSql('COMMENT ON COLUMN request.status IS \'Trạng thái hiện tại của đề xuất: pending, rejected, approved, cancelled\'');
        $this->addSql('COMMENT ON COLUMN request.requester_department_snapshot IS \'Snapshot JSON của bộ phận chính của người tạo tại thời điểm tạo đề xuất\'');
        $this->addSql('COMMENT ON COLUMN request.requester_position_snapshot IS \'Snapshot JSON của chức vụ chính của người tạo tại thời điểm tạo đề xuất\'');
        $this->addSql('COMMENT ON COLUMN request.current_step_no IS \'Bước duyệt hiện tại, có thể mở rộng duyệt nhiều cấp\'');
        $this->addSql('COMMENT ON COLUMN request.revision_no IS \'Số lần gửi lại đề xuất sau khi bị từ chối\'');
        $this->addSql('COMMENT ON COLUMN request.title IS \'Tiêu đề của đề xuất\'');
        $this->addSql('COMMENT ON COLUMN request.summary IS \'Mô tả tóm tắt của đề xuất để hiển thị ở danh sách\'');
        $this->addSql('COMMENT ON COLUMN request.payload IS \'Payload JSON chứa dữ liệu chi tiết riêng theo từng loại đề xuất\'');
        $this->addSql('COMMENT ON COLUMN request.last_reject_reason IS \'Lý do từ chối gần nhất của đề xuất\'');
        $this->addSql('COMMENT ON COLUMN request.source_ref_type IS \'Loại bản ghi nguồn đã tự động sinh ra đề xuất\'');
        $this->addSql('COMMENT ON COLUMN request.source_ref_id IS \'ID bản ghi nguồn đã tự động sinh ra đề xuất\'');
        $this->addSql('COMMENT ON COLUMN request.target_ref_type IS \'Loại dữ liệu đích được tạo hoặc cập nhật sau khi duyệt\'');
        $this->addSql('COMMENT ON COLUMN request.target_ref_id IS \'ID dữ liệu đích được tạo hoặc cập nhật sau khi duyệt\'');
        $this->addSql('COMMENT ON COLUMN request.submitted_at IS \'Thời điểm đề xuất được gửi đi để chờ duyệt\'');
        $this->addSql('COMMENT ON COLUMN request.approved_at IS \'Thời điểm đề xuất được duyệt\'');
        $this->addSql('COMMENT ON COLUMN request.rejected_at IS \'Thời điểm đề xuất bị từ chối gần nhất\'');
        $this->addSql('COMMENT ON COLUMN request.cancelled_at IS \'Thời điểm đề xuất bị hủy\'');
        $this->addSql('COMMENT ON COLUMN request.requester_id IS \'Người tạo đề xuất\'');
        $this->addSql('COMMENT ON COLUMN request.current_approver_id IS \'Người duyệt hiện tại của đề xuất\'');
        $this->addSql('CREATE TABLE request_approval_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, step_no INT NOT NULL, revision_no INT NOT NULL, status VARCHAR(30) NOT NULL, decision_comment TEXT DEFAULT NULL, acted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_id INT NOT NULL, approver_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F7A946C427EB8A5 ON request_approval_step (request_id)');
        $this->addSql('CREATE INDEX IDX_1F7A946CBB23766C ON request_approval_step (approver_id)');
        $this->addSql('COMMENT ON COLUMN request_approval_step.step_no IS \'Số thứ tự bước duyệt\'');
        $this->addSql('COMMENT ON COLUMN request_approval_step.revision_no IS \'Lần gửi đề xuất mà bước duyệt này tương ứng\'');
        $this->addSql('COMMENT ON COLUMN request_approval_step.status IS \'Trạng thái của bước duyệt: pending, approved, rejected, cancelled\'');
        $this->addSql('COMMENT ON COLUMN request_approval_step.decision_comment IS \'Ghi chú hoặc lý do xử lý của người duyệt\'');
        $this->addSql('COMMENT ON COLUMN request_approval_step.acted_at IS \'Thời điểm người duyệt thực hiện hành động ở bước này\'');
        $this->addSql('COMMENT ON COLUMN request_approval_step.approver_id IS \'Người chịu trách nhiệm duyệt ở bước này\'');
        $this->addSql('CREATE TABLE request_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(50) NOT NULL, actor_type VARCHAR(20) DEFAULT \'user\' NOT NULL, step_no INT DEFAULT NULL, revision_no INT DEFAULT NULL, from_status VARCHAR(30) DEFAULT NULL, to_status VARCHAR(30) DEFAULT NULL, comment TEXT DEFAULT NULL, payload_snapshot JSON DEFAULT NULL, meta JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_66B9B682427EB8A5 ON request_event (request_id)');
        $this->addSql('CREATE INDEX IDX_66B9B68210DAF24A ON request_event (actor_id)');
        $this->addSql('COMMENT ON COLUMN request_event.event_type IS \'Loại sự kiện timeline: created, submitted, approved, rejected...\'');
        $this->addSql('COMMENT ON COLUMN request_event.actor_type IS \'Loại actor tạo ra sự kiện: user, system, job\'');
        $this->addSql('COMMENT ON COLUMN request_event.step_no IS \'Bước duyệt liên quan đến sự kiện này\'');
        $this->addSql('COMMENT ON COLUMN request_event.revision_no IS \'Lần gửi đề xuất liên quan đến sự kiện này\'');
        $this->addSql('COMMENT ON COLUMN request_event.from_status IS \'Trạng thái trước khi sự kiện xảy ra\'');
        $this->addSql('COMMENT ON COLUMN request_event.to_status IS \'Trạng thái sau khi sự kiện xảy ra\'');
        $this->addSql('COMMENT ON COLUMN request_event.comment IS \'Nội dung ghi chú đi kèm sự kiện timeline\'');
        $this->addSql('COMMENT ON COLUMN request_event.payload_snapshot IS \'Snapshot payload của đề xuất tại thời điểm sự kiện diễn ra\'');
        $this->addSql('COMMENT ON COLUMN request_event.meta IS \'Metadata mở rộng của sự kiện timeline\'');
        $this->addSql('COMMENT ON COLUMN request_event.created_at IS \'Thời điểm sự kiện timeline được ghi nhận\'');
        $this->addSql('COMMENT ON COLUMN request_event.actor_id IS \'Người thực hiện hành động tạo ra sự kiện timeline này\'');
        $this->addSql('CREATE TABLE request_watcher (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, watch_type VARCHAR(20) DEFAULT \'viewer\', notify_on_submit BOOLEAN DEFAULT true NOT NULL, notify_on_reject BOOLEAN DEFAULT true NOT NULL, notify_on_approve BOOLEAN DEFAULT true NOT NULL, notify_on_comment BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98AB94FB427EB8A5 ON request_watcher (request_id)');
        $this->addSql('CREATE INDEX IDX_98AB94FBA76ED395 ON request_watcher (user_id)');
        $this->addSql('COMMENT ON COLUMN request_watcher.watch_type IS \'Loại theo dõi: viewer, cc, observer...\'');
        $this->addSql('COMMENT ON COLUMN request_watcher.notify_on_submit IS \'Có nhận thông báo khi đề xuất được gửi đi hay không\'');
        $this->addSql('COMMENT ON COLUMN request_watcher.notify_on_reject IS \'Có nhận thông báo khi đề xuất bị từ chối hay không\'');
        $this->addSql('COMMENT ON COLUMN request_watcher.notify_on_approve IS \'Có nhận thông báo khi đề xuất được duyệt hay không\'');
        $this->addSql('COMMENT ON COLUMN request_watcher.notify_on_comment IS \'Có nhận thông báo khi có trao đổi hoặc comment hay không\'');
        $this->addSql('COMMENT ON COLUMN request_watcher.created_at IS \'Thời điểm người theo dõi được thêm vào đề xuất\'');
        $this->addSql('ALTER TABLE request ADD CONSTRAINT FK_3B978F9FED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request ADD CONSTRAINT FK_3B978F9F5F7DDB5 FOREIGN KEY (current_approver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_approval_step ADD CONSTRAINT FK_1F7A946C427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_approval_step ADD CONSTRAINT FK_1F7A946CBB23766C FOREIGN KEY (approver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_event ADD CONSTRAINT FK_66B9B682427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_event ADD CONSTRAINT FK_66B9B68210DAF24A FOREIGN KEY (actor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_watcher ADD CONSTRAINT FK_98AB94FB427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_watcher ADD CONSTRAINT FK_98AB94FBA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE request DROP CONSTRAINT FK_3B978F9FED442CF4');
        $this->addSql('ALTER TABLE request DROP CONSTRAINT FK_3B978F9F5F7DDB5');
        $this->addSql('ALTER TABLE request_approval_step DROP CONSTRAINT FK_1F7A946C427EB8A5');
        $this->addSql('ALTER TABLE request_approval_step DROP CONSTRAINT FK_1F7A946CBB23766C');
        $this->addSql('ALTER TABLE request_event DROP CONSTRAINT FK_66B9B682427EB8A5');
        $this->addSql('ALTER TABLE request_event DROP CONSTRAINT FK_66B9B68210DAF24A');
        $this->addSql('ALTER TABLE request_watcher DROP CONSTRAINT FK_98AB94FB427EB8A5');
        $this->addSql('ALTER TABLE request_watcher DROP CONSTRAINT FK_98AB94FBA76ED395');
        $this->addSql('DROP TABLE request');
        $this->addSql('DROP TABLE request_approval_step');
        $this->addSql('DROP TABLE request_event');
        $this->addSql('DROP TABLE request_watcher');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
    }
}
