<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260124070928 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ca_lam_viec (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gio_bat_dau VARCHAR(255) NOT NULL, gio_ket_thuc VARCHAR(255) NOT NULL, ghi_chu VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, thoi_gian_lam_viec_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50B0B6E82DBE3FA2 ON ca_lam_viec (thoi_gian_lam_viec_id)');
        $this->addSql('CREATE TABLE thoi_gian_lam_viec (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, thu VARCHAR(255) NOT NULL, gio_bat_dau VARCHAR(255) NOT NULL, gio_ket_thuc VARCHAR(255) NOT NULL, ghi_chu VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE ca_lam_viec ADD CONSTRAINT FK_50B0B6E82DBE3FA2 FOREIGN KEY (thoi_gian_lam_viec_id) REFERENCES thoi_gian_lam_viec (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ca_lam_viec DROP CONSTRAINT FK_50B0B6E82DBE3FA2');
        $this->addSql('DROP TABLE ca_lam_viec');
        $this->addSql('DROP TABLE thoi_gian_lam_viec');
    }
}
