<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260913083733 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sale_order (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, order_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subtotal NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, discount_amount NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, tax_amount NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, total_amount NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, payment_method VARCHAR(30) DEFAULT NULL, payment_status SMALLINT DEFAULT 0 NOT NULL, status SMALLINT DEFAULT 1 NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, branch_id INT DEFAULT NULL, dining_table_id INT DEFAULT NULL, cashier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_25F5CB1BDCD6CC49 ON sale_order (branch_id)');
        $this->addSql('CREATE INDEX IDX_25F5CB1B695B08DC ON sale_order (dining_table_id)');
        $this->addSql('CREATE INDEX IDX_25F5CB1B2EDB0489 ON sale_order (cashier_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SALE_ORDER_CODE ON sale_order (code) WHERE deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN sale_order.id IS \'Khóa chính đơn bán hàng\'');
        $this->addSql('COMMENT ON COLUMN sale_order.code IS \'Mã đơn bán hàng (HD-YYYYMMDD-XXXX)\'');
        $this->addSql('COMMENT ON COLUMN sale_order.order_date IS \'Thời điểm tạo đơn\'');
        $this->addSql('COMMENT ON COLUMN sale_order.subtotal IS \'Tạm tính tiền hàng\'');
        $this->addSql('COMMENT ON COLUMN sale_order.discount_amount IS \'Tiền giảm giá/chiết khấu\'');
        $this->addSql('COMMENT ON COLUMN sale_order.tax_amount IS \'Tiền thuế VAT\'');
        $this->addSql('COMMENT ON COLUMN sale_order.total_amount IS \'Tổng tiền thanh toán thực tế\'');
        $this->addSql('COMMENT ON COLUMN sale_order.payment_method IS \'Phương thức thanh toán\'');
        $this->addSql('COMMENT ON COLUMN sale_order.payment_status IS \'Trạng thái thanh toán (0: Chưa TT, 1: Đã TT, 2: Hoàn tiền)\'');
        $this->addSql('COMMENT ON COLUMN sale_order.status IS \'Trạng thái đơn hàng (1: Hoàn thành, 2: Đang xử lý, 0: Đã hủy)\'');
        $this->addSql('COMMENT ON COLUMN sale_order.note IS \'Ghi chú đơn hàng\'');
        $this->addSql('CREATE TABLE sale_order_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(10, 2) DEFAULT \'1.00\' NOT NULL, unit_price NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, subtotal NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, note VARCHAR(500) DEFAULT NULL, product_snapshot JSON NOT NULL, variant_snapshot JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sale_order_id BIGINT NOT NULL, business_product_id INT DEFAULT NULL, variant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AFBEFB4D93EB8192 ON sale_order_item (sale_order_id)');
        $this->addSql('CREATE INDEX IDX_AFBEFB4D85276EF1 ON sale_order_item (business_product_id)');
        $this->addSql('CREATE INDEX IDX_AFBEFB4D3B69A9AF ON sale_order_item (variant_id)');
        $this->addSql('COMMENT ON COLUMN sale_order_item.id IS \'Khóa chính chi tiết đơn bán\'');
        $this->addSql('COMMENT ON COLUMN sale_order_item.quantity IS \'Số lượng bán\'');
        $this->addSql('COMMENT ON COLUMN sale_order_item.unit_price IS \'Đơn giá bán tại thời điểm tạo đơn\'');
        $this->addSql('COMMENT ON COLUMN sale_order_item.subtotal IS \'Thành tiền = quantity * unit_price\'');
        $this->addSql('COMMENT ON COLUMN sale_order_item.note IS \'Ghi chú cho món\'');
        $this->addSql('COMMENT ON COLUMN sale_order_item.product_snapshot IS \'Toàn bộ dữ liệu snapshot của BusinessProduct\'');
        $this->addSql('COMMENT ON COLUMN sale_order_item.variant_snapshot IS \'Toàn bộ dữ liệu snapshot của BusinessProductVariant\'');
        $this->addSql('COMMENT ON COLUMN sale_order_item.sale_order_id IS \'Khóa chính đơn bán hàng\'');
        $this->addSql('ALTER TABLE sale_order ADD CONSTRAINT FK_25F5CB1BDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_order ADD CONSTRAINT FK_25F5CB1B695B08DC FOREIGN KEY (dining_table_id) REFERENCES dining_table (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_order ADD CONSTRAINT FK_25F5CB1B2EDB0489 FOREIGN KEY (cashier_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_order_item ADD CONSTRAINT FK_AFBEFB4D93EB8192 FOREIGN KEY (sale_order_id) REFERENCES sale_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_order_item ADD CONSTRAINT FK_AFBEFB4D85276EF1 FOREIGN KEY (business_product_id) REFERENCES business_product (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_order_item ADD CONSTRAINT FK_AFBEFB4D3B69A9AF FOREIGN KEY (variant_id) REFERENCES business_product_variant (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sale_order DROP CONSTRAINT FK_25F5CB1BDCD6CC49');
        $this->addSql('ALTER TABLE sale_order DROP CONSTRAINT FK_25F5CB1B695B08DC');
        $this->addSql('ALTER TABLE sale_order DROP CONSTRAINT FK_25F5CB1B2EDB0489');
        $this->addSql('ALTER TABLE sale_order_item DROP CONSTRAINT FK_AFBEFB4D93EB8192');
        $this->addSql('ALTER TABLE sale_order_item DROP CONSTRAINT FK_AFBEFB4D85276EF1');
        $this->addSql('ALTER TABLE sale_order_item DROP CONSTRAINT FK_AFBEFB4D3B69A9AF');
        $this->addSql('DROP TABLE sale_order');
        $this->addSql('DROP TABLE sale_order_item');
    }
}
