<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260901090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add finished-goods stock transfer document and inventory links';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE stock_transfer (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                request_id INT NOT NULL,
                source_warehouse_id INT NOT NULL,
                destination_warehouse_id INT NOT NULL,
                executed_by INT NOT NULL,
                code VARCHAR(50) NOT NULL,
                warehouse_snapshot JSONB NOT NULL,
                items_snapshot JSONB NOT NULL,
                snapshot_version INT DEFAULT 1 NOT NULL,
                reason TEXT NOT NULL,
                note TEXT DEFAULT NULL,
                status VARCHAR(30) DEFAULT 'COMPLETED' NOT NULL,
                executed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_by INT DEFAULT NULL,
                updated_by INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STOCK_TRANSFER_CODE ON stock_transfer (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STOCK_TRANSFER_REQUEST ON stock_transfer (request_id)');
        $this->addSql('CREATE INDEX IDX_FF2F782866A3066 ON stock_transfer (source_warehouse_id)');
        $this->addSql('CREATE INDEX IDX_FF2F782E1AE3711 ON stock_transfer (destination_warehouse_id)');
        $this->addSql('CREATE INDEX IDX_FF2F782358DAC4B ON stock_transfer (executed_by)');
        $this->addSql("COMMENT ON COLUMN stock_transfer.code IS 'Mã phiếu chuyển kho'");
        $this->addSql("COMMENT ON COLUMN stock_transfer.warehouse_snapshot IS 'Snapshot kho nguồn và kho đích'");
        $this->addSql("COMMENT ON COLUMN stock_transfer.items_snapshot IS 'Snapshot các dòng hàng đã thực hiện chuyển kho'");
        $this->addSql("COMMENT ON COLUMN stock_transfer.snapshot_version IS 'Phiên bản cấu trúc snapshot'");
        $this->addSql("COMMENT ON COLUMN stock_transfer.reason IS 'Lý do chuyển kho'");
        $this->addSql('ALTER TABLE stock_transfer ADD CONSTRAINT FK_FF2F782427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_transfer ADD CONSTRAINT FK_FF2F782866A3066 FOREIGN KEY (source_warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_transfer ADD CONSTRAINT FK_FF2F782E1AE3711 FOREIGN KEY (destination_warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_transfer ADD CONSTRAINT FK_FF2F782358DAC4B FOREIGN KEY (executed_by) REFERENCES "user" (id) NOT DEFERRABLE');

        $this->addSql('ALTER TABLE inventory_movement ADD stock_transfer_id BIGINT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_40972F668CBEEE9B ON inventory_movement (stock_transfer_id)');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F668CBEEE9B FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfer (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INVENTORY_BALANCE_WAREHOUSE_MERCHANDISE_LOT ON inventory_balance (warehouse_id, merchandise_id, lot_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX UNIQ_INVENTORY_BALANCE_WAREHOUSE_MERCHANDISE_LOT');
        $this->addSql('ALTER TABLE inventory_movement DROP CONSTRAINT FK_40972F668CBEEE9B');
        $this->addSql('DROP INDEX IDX_40972F668CBEEE9B');
        $this->addSql('ALTER TABLE inventory_movement DROP stock_transfer_id');
        $this->addSql('DROP TABLE stock_transfer');
    }
}
