<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260509083628 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE work_shift_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note TEXT DEFAULT NULL, work_shift_id INT DEFAULT NULL, member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_21872E4F6EC53652 ON work_shift_assignment (work_shift_id)');
        $this->addSql('CREATE INDEX IDX_21872E4F7597D3FE ON work_shift_assignment (member_id)');
        $this->addSql('ALTER TABLE work_shift_assignment ADD CONSTRAINT FK_21872E4F6EC53652 FOREIGN KEY (work_shift_id) REFERENCES work_shift (id)');
        $this->addSql('ALTER TABLE work_shift_assignment ADD CONSTRAINT FK_21872E4F7597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE work_shift_assignment DROP CONSTRAINT FK_21872E4F6EC53652');
        $this->addSql('ALTER TABLE work_shift_assignment DROP CONSTRAINT FK_21872E4F7597D3FE');
        $this->addSql('DROP TABLE work_shift_assignment');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
    }
}
