<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317133142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, employment_type VARCHAR(255) DEFAULT \'FULL_TIME\', min_salary NUMERIC(15, 2) DEFAULT NULL, max_salary NUMERIC(15, 2) DEFAULT NULL, currency VARCHAR(255) DEFAULT NULL, probation_months INT DEFAULT 2, probation_salary_rate INT DEFAULT 85, annual_leave_days INT DEFAULT 12, review_cycle_months INT DEFAULT 12, notice_period_days INT DEFAULT 12, allowances JSON DEFAULT NULL, status INT DEFAULT 1, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, department_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_462CE4F5AE80F5DF ON position (department_id)');
        $this->addSql('COMMENT ON COLUMN position.employment_type IS \'Hinh thuc lam viec (FULL_TIME, PART_TIME...)\'');
        $this->addSql('COMMENT ON COLUMN position.probation_months IS \'So thang thu viec tieu chuan\'');
        $this->addSql('COMMENT ON COLUMN position.probation_salary_rate IS \'Ty le huong luong thu viec (%)\'');
        $this->addSql('COMMENT ON COLUMN position.annual_leave_days IS \'So ngay nghi phep nam tieu chuan\'');
        $this->addSql('COMMENT ON COLUMN position.review_cycle_months IS \'So thang danh gia luong nam tieu chuan\'');
        $this->addSql('COMMENT ON COLUMN position.notice_period_days IS \'So ngay thong bao truoc khi nghi viec\'');
        $this->addSql('COMMENT ON COLUMN position.allowances IS \'Danh sach phu cap (JSON)\'');
        $this->addSql('COMMENT ON COLUMN position.status IS \'1: active, 0: inactive\'');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id)');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('COMMENT ON COLUMN "user".is_ngoai_gio IS \'0: cho phép ngoài giờ, 1: không cho phép ngoài giờ\'');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position DROP CONSTRAINT FK_462CE4F5AE80F5DF');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('COMMENT ON COLUMN "user".is_ngoai_gio IS \'0: cho phép ngoại giờ, 1: không cho phép ngoại giờ\'');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
    }
}
