<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708135002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE business_product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, target_profit_margin NUMERIC(5, 2) DEFAULT NULL, status SMALLINT DEFAULT 1 NOT NULL, sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, category_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8E79BFE012469DE2 ON business_product (category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BUSINESS_PRODUCT_CODE ON business_product (code) WHERE deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN business_product.code IS \'Mã sản phẩm\'');
        $this->addSql('COMMENT ON COLUMN business_product.name IS \'Tên sản phẩm\'');
        $this->addSql('COMMENT ON COLUMN business_product.description IS \'Mô tả\'');
        $this->addSql('COMMENT ON COLUMN business_product.notes IS \'Ghi chú\'');
        $this->addSql('COMMENT ON COLUMN business_product.image_url IS \'Đường dẫn ảnh\'');
        $this->addSql('COMMENT ON COLUMN business_product.target_profit_margin IS \'Tỷ lệ lợi nhuận mục tiêu (%)\'');
        $this->addSql('COMMENT ON COLUMN business_product.status IS \'Trạng thái (1: active, 0: inactive)\'');
        $this->addSql('COMMENT ON COLUMN business_product.sort_order IS \'Thứ tự sắp xếp\'');
        $this->addSql('CREATE TABLE business_product_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, barcode VARCHAR(255) DEFAULT NULL, selling_price NUMERIC(15, 2) NOT NULL, suggested_price_snapshot NUMERIC(15, 2) DEFAULT NULL, cost_price_snapshot NUMERIC(15, 2) DEFAULT NULL, target_profit_margin_snapshot NUMERIC(5, 2) DEFAULT NULL, currency VARCHAR(10) DEFAULT \'VND\' NOT NULL, is_default BOOLEAN DEFAULT false NOT NULL, status SMALLINT DEFAULT 1 NOT NULL, sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, business_product_id INT NOT NULL, unit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F21D160285276EF1 ON business_product_variant (business_product_id)');
        $this->addSql('CREATE INDEX IDX_F21D1602F8BD700D ON business_product_variant (unit_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BUSINESS_PRODUCT_VARIANT_CODE ON business_product_variant (code) WHERE deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN business_product_variant.code IS \'Mã SKU / Mã biến thể\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.name IS \'Tên biến thể\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.barcode IS \'Mã vạch\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.selling_price IS \'Giá bán\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.suggested_price_snapshot IS \'Giá gợi ý tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.cost_price_snapshot IS \'Giá vốn tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.target_profit_margin_snapshot IS \'Tỷ lệ lợi nhuận mục tiêu tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.currency IS \'Loại tiền tệ\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.is_default IS \'Là biến thể mặc định\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.status IS \'Trạng thái (1: active, 0: inactive)\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant.sort_order IS \'Thứ tự sắp xếp\'');
        $this->addSql('CREATE TABLE business_product_variant_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price NUMERIC(15, 2) NOT NULL, currency VARCHAR(10) DEFAULT \'VND\' NOT NULL, effective_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, effective_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_current BOOLEAN DEFAULT true NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, variant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F6AB25903B69A9AF ON business_product_variant_price (variant_id)');
        $this->addSql('COMMENT ON COLUMN business_product_variant_price.price IS \'Giá bán\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_price.currency IS \'Loại tiền tệ\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_price.effective_from IS \'Ngày bắt đầu hiệu lực\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_price.effective_to IS \'Ngày hết hiệu lực\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_price.is_current IS \'Giá hiện tại đang áp dụng\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_price.note IS \'Ghi chú\'');
        $this->addSql('CREATE TABLE business_product_variant_recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version INT DEFAULT 1 NOT NULL, total_cost_snapshot NUMERIC(15, 2) DEFAULT NULL, suggested_price_snapshot NUMERIC(15, 2) DEFAULT NULL, target_profit_margin_snapshot NUMERIC(5, 2) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, status SMALLINT DEFAULT 1 NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, variant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5B42B043B69A9AF ON business_product_variant_recipe (variant_id)');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe.version IS \'Phiên bản công thức\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe.total_cost_snapshot IS \'Tổng chi phí tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe.suggested_price_snapshot IS \'Giá bán gợi ý tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe.target_profit_margin_snapshot IS \'Tỷ lệ lợi nhuận mục tiêu tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe.is_active IS \'Công thức đang hoạt động\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe.status IS \'Trạng thái (1: active, 0: inactive)\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe.notes IS \'Ghi chú\'');
        $this->addSql('CREATE TABLE business_product_variant_recipe_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(10, 4) NOT NULL, factor_to_base_snapshot NUMERIC(10, 4) NOT NULL, base_quantity_snapshot NUMERIC(10, 4) NOT NULL, unit_cost_snapshot NUMERIC(15, 4) DEFAULT NULL, line_cost_snapshot NUMERIC(15, 2) DEFAULT NULL, waste_rate NUMERIC(5, 2) DEFAULT \'0.00\' NOT NULL, sort_order INT DEFAULT 0 NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, recipe_id INT NOT NULL, finished_product_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE95BC6C59D8A214 ON business_product_variant_recipe_item (recipe_id)');
        $this->addSql('CREATE INDEX IDX_FE95BC6C380E9C02 ON business_product_variant_recipe_item (finished_product_id)');
        $this->addSql('CREATE INDEX IDX_FE95BC6CF8BD700D ON business_product_variant_recipe_item (unit_id)');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe_item.quantity IS \'Số lượng thành phẩm / nguyên liệu sử dụng\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe_item.factor_to_base_snapshot IS \'Hệ số quy đổi sang đơn vị chuẩn tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe_item.base_quantity_snapshot IS \'Số lượng chuẩn tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe_item.unit_cost_snapshot IS \'Giá vốn đơn vị tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe_item.line_cost_snapshot IS \'Giá vốn dòng tại thời điểm lưu\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe_item.waste_rate IS \'Tỷ lệ hao hụt (%)\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe_item.sort_order IS \'Thứ tự sắp xếp\'');
        $this->addSql('COMMENT ON COLUMN business_product_variant_recipe_item.notes IS \'Ghi chú\'');
        $this->addSql('ALTER TABLE business_product ADD CONSTRAINT FK_8E79BFE012469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business_product_variant ADD CONSTRAINT FK_F21D160285276EF1 FOREIGN KEY (business_product_id) REFERENCES business_product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business_product_variant ADD CONSTRAINT FK_F21D1602F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business_product_variant_price ADD CONSTRAINT FK_F6AB25903B69A9AF FOREIGN KEY (variant_id) REFERENCES business_product_variant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business_product_variant_recipe ADD CONSTRAINT FK_D5B42B043B69A9AF FOREIGN KEY (variant_id) REFERENCES business_product_variant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business_product_variant_recipe_item ADD CONSTRAINT FK_FE95BC6C59D8A214 FOREIGN KEY (recipe_id) REFERENCES business_product_variant_recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business_product_variant_recipe_item ADD CONSTRAINT FK_FE95BC6C380E9C02 FOREIGN KEY (finished_product_id) REFERENCES merchandise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business_product_variant_recipe_item ADD CONSTRAINT FK_FE95BC6CF8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_branch_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BRANCH_CODE ON branch (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_category_slug');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORY_SLUG ON category (slug) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_department_ma_bo_phan');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DEPARTMENT_MA_BO_PHAN ON department (ma_bo_phan) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_merchandise_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MERCHANDISE_CODE ON merchandise (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_position_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_CODE ON "position" (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_provider_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROVIDER_CODE ON provider (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_unit_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_UNIT_CODE ON unit (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('DROP INDEX uniq_user_ma_nhan_vien');
        $this->addSql('DROP INDEX uniq_user_phone');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_MA_NHAN_VIEN ON "user" (ma_nhan_vien) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_PHONE ON "user" (phone) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_warehouse_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WAREHOUSE_CODE ON warehouse (code) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE business_product DROP CONSTRAINT FK_8E79BFE012469DE2');
        $this->addSql('ALTER TABLE business_product_variant DROP CONSTRAINT FK_F21D160285276EF1');
        $this->addSql('ALTER TABLE business_product_variant DROP CONSTRAINT FK_F21D1602F8BD700D');
        $this->addSql('ALTER TABLE business_product_variant_price DROP CONSTRAINT FK_F6AB25903B69A9AF');
        $this->addSql('ALTER TABLE business_product_variant_recipe DROP CONSTRAINT FK_D5B42B043B69A9AF');
        $this->addSql('ALTER TABLE business_product_variant_recipe_item DROP CONSTRAINT FK_FE95BC6C59D8A214');
        $this->addSql('ALTER TABLE business_product_variant_recipe_item DROP CONSTRAINT FK_FE95BC6C380E9C02');
        $this->addSql('ALTER TABLE business_product_variant_recipe_item DROP CONSTRAINT FK_FE95BC6CF8BD700D');
        $this->addSql('DROP TABLE business_product');
        $this->addSql('DROP TABLE business_product_variant');
        $this->addSql('DROP TABLE business_product_variant_price');
        $this->addSql('DROP TABLE business_product_variant_recipe');
        $this->addSql('DROP TABLE business_product_variant_recipe_item');
        $this->addSql('DROP INDEX UNIQ_BRANCH_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_branch_code ON branch (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_CATEGORY_SLUG');
        $this->addSql('CREATE UNIQUE INDEX uniq_category_slug ON category (slug) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_DEPARTMENT_MA_BO_PHAN');
        $this->addSql('CREATE UNIQUE INDEX uniq_department_ma_bo_phan ON department (ma_bo_phan) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_MERCHANDISE_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_merchandise_code ON merchandise (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_POSITION_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_code ON "position" (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_PROVIDER_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_provider_code ON provider (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_UNIT_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_unit_code ON unit (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('DROP INDEX UNIQ_USER_MA_NHAN_VIEN');
        $this->addSql('DROP INDEX UNIQ_USER_PHONE');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_ma_nhan_vien ON "user" (ma_nhan_vien) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_phone ON "user" (phone) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_WAREHOUSE_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_warehouse_code ON warehouse (code) WHERE (deleted_at IS NULL)');
    }
}
