<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412092514 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fixed_schedule_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F0C6B937597D3FE ON fixed_schedule_group (member_id)');
        $this->addSql('CREATE TABLE fixed_schedule_override (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AFCE2437597D3FE ON fixed_schedule_override (member_id)');
        $this->addSql('ALTER TABLE fixed_schedule_group ADD CONSTRAINT FK_3F0C6B937597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE fixed_schedule_override ADD CONSTRAINT FK_6AFCE2437597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE fixed_schedule DROP CONSTRAINT fk_65fa44a17597d3fe');
        $this->addSql('DROP INDEX idx_65fa44a17597d3fe');
        $this->addSql('ALTER TABLE fixed_schedule ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE fixed_schedule ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE fixed_schedule ADD updated_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fixed_schedule ADD fixed_schedule_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fixed_schedule RENAME COLUMN member_id TO created_by');
        $this->addSql('ALTER TABLE fixed_schedule ADD CONSTRAINT FK_65FA44A116AB3DE1 FOREIGN KEY (fixed_schedule_group_id) REFERENCES fixed_schedule_group (id)');
        $this->addSql('CREATE INDEX IDX_65FA44A116AB3DE1 ON fixed_schedule (fixed_schedule_group_id)');
        $this->addSql('ALTER TABLE leave_schedule ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE leave_schedule ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE leave_schedule ADD created_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE leave_schedule ADD updated_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE shift_assignment ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE shift_assignment ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE shift_assignment ADD created_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE shift_assignment ADD updated_by INT DEFAULT NULL');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fixed_schedule_group DROP CONSTRAINT FK_3F0C6B937597D3FE');
        $this->addSql('ALTER TABLE fixed_schedule_override DROP CONSTRAINT FK_6AFCE2437597D3FE');
        $this->addSql('DROP TABLE fixed_schedule_group');
        $this->addSql('DROP TABLE fixed_schedule_override');
        $this->addSql('ALTER TABLE fixed_schedule DROP CONSTRAINT FK_65FA44A116AB3DE1');
        $this->addSql('DROP INDEX IDX_65FA44A116AB3DE1');
        $this->addSql('ALTER TABLE fixed_schedule ADD member_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fixed_schedule DROP created_at');
        $this->addSql('ALTER TABLE fixed_schedule DROP updated_at');
        $this->addSql('ALTER TABLE fixed_schedule DROP created_by');
        $this->addSql('ALTER TABLE fixed_schedule DROP updated_by');
        $this->addSql('ALTER TABLE fixed_schedule DROP fixed_schedule_group_id');
        $this->addSql('ALTER TABLE fixed_schedule ADD CONSTRAINT fk_65fa44a17597d3fe FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_65fa44a17597d3fe ON fixed_schedule (member_id)');
        $this->addSql('ALTER TABLE leave_schedule DROP created_at');
        $this->addSql('ALTER TABLE leave_schedule DROP updated_at');
        $this->addSql('ALTER TABLE leave_schedule DROP created_by');
        $this->addSql('ALTER TABLE leave_schedule DROP updated_by');
        $this->addSql('ALTER TABLE shift_assignment DROP created_at');
        $this->addSql('ALTER TABLE shift_assignment DROP updated_at');
        $this->addSql('ALTER TABLE shift_assignment DROP created_by');
        $this->addSql('ALTER TABLE shift_assignment DROP updated_by');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
    }
}
