<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260411074900 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fixed_schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT DEFAULT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65FA44A17597D3FE ON fixed_schedule (member_id)');
        $this->addSql('CREATE TABLE leave_schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) DEFAULT NULL, start_datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, reason TEXT DEFAULT NULL, member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_641039587597D3FE ON leave_schedule (member_id)');
        $this->addSql('CREATE TABLE shift_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, work_date DATE DEFAULT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_47A0F957597D3FE ON shift_assignment (member_id)');
        $this->addSql('ALTER TABLE fixed_schedule ADD CONSTRAINT FK_65FA44A17597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE leave_schedule ADD CONSTRAINT FK_641039587597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE shift_assignment ADD CONSTRAINT FK_47A0F957597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fixed_schedule DROP CONSTRAINT FK_65FA44A17597D3FE');
        $this->addSql('ALTER TABLE leave_schedule DROP CONSTRAINT FK_641039587597D3FE');
        $this->addSql('ALTER TABLE shift_assignment DROP CONSTRAINT FK_47A0F957597D3FE');
        $this->addSql('DROP TABLE fixed_schedule');
        $this->addSql('DROP TABLE leave_schedule');
        $this->addSql('DROP TABLE shift_assignment');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
    }
}
