<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627083047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE merchandise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, profit NUMERIC(10, 2) DEFAULT NULL, description TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, stock_alert_quantity NUMERIC(10, 2) DEFAULT NULL, status SMALLINT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, category_id BIGINT DEFAULT NULL, base_unit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D043D1A412469DE2 ON merchandise (category_id)');
        $this->addSql('CREATE INDEX IDX_D043D1A4CCBBC969 ON merchandise (base_unit_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MERCHANDISE_CODE ON merchandise (code) WHERE deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN merchandise.code IS \'Mã hàng hóa\'');
        $this->addSql('COMMENT ON COLUMN merchandise.name IS \'Tên hàng hóa\'');
        $this->addSql('COMMENT ON COLUMN merchandise.type IS \'Loại hàng hóa (finished_product, ingredient)\'');
        $this->addSql('COMMENT ON COLUMN merchandise.profit IS \'% lợi nhuận mặc định\'');
        $this->addSql('COMMENT ON COLUMN merchandise.description IS \'Mô tả\'');
        $this->addSql('COMMENT ON COLUMN merchandise.notes IS \'Ghi chú\'');
        $this->addSql('COMMENT ON COLUMN merchandise.stock_alert_quantity IS \'Số lượng cảnh báo theo base unit\'');
        $this->addSql('COMMENT ON COLUMN merchandise.status IS \'Trạng thái (1 active, 0 inactive)\'');
        $this->addSql('CREATE TABLE merchandise_provider (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unit_config_mode VARCHAR(50) DEFAULT \'general\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, merchandise_id INT NOT NULL, provider_id INT NOT NULL, default_purchase_unit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A826E055CFC6D428 ON merchandise_provider (merchandise_id)');
        $this->addSql('CREATE INDEX IDX_A826E055A53A8AA ON merchandise_provider (provider_id)');
        $this->addSql('CREATE INDEX IDX_A826E0556C9A7223 ON merchandise_provider (default_purchase_unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_provider.unit_config_mode IS \'general hoặc custom\'');
        $this->addSql('CREATE TABLE merchandise_provider_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unit_label_snapshot VARCHAR(255) DEFAULT NULL, factor_to_base_snapshot NUMERIC(10, 4) DEFAULT NULL, price NUMERIC(15, 2) NOT NULL, discount_rate NUMERIC(5, 2) DEFAULT \'0.00\', discount_amount NUMERIC(15, 2) DEFAULT \'0.00\', price_after_discount NUMERIC(15, 2) NOT NULL, currency VARCHAR(10) DEFAULT \'VND\' NOT NULL, effective_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, effective_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_default BOOLEAN DEFAULT false NOT NULL, status SMALLINT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, merchandise_provider_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_66556CE480455FD2 ON merchandise_provider_price (merchandise_provider_id)');
        $this->addSql('CREATE INDEX IDX_66556CE4F8BD700D ON merchandise_provider_price (unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.unit_label_snapshot IS \'Ví dụ: Thùng 36 chai\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.factor_to_base_snapshot IS \'Snapshot hệ số tại thời điểm tạo giá\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.price IS \'Giá gốc\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.discount_rate IS \'% giảm giá\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.discount_amount IS \'Số tiền giảm trực tiếp\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.price_after_discount IS \'Giá sau giảm\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.currency IS \'VND\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.effective_from IS \'Ngày bắt đầu\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.effective_to IS \'Ngày kết thúc\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.is_default IS \'Giá mặc định\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_price.status IS \'Trạng thái giá\'');
        $this->addSql('CREATE TABLE merchandise_provider_unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, factor_to_base NUMERIC(10, 4) NOT NULL, level INT DEFAULT 0 NOT NULL, label VARCHAR(255) DEFAULT NULL, is_base BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, merchandise_provider_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD0C717880455FD2 ON merchandise_provider_unit (merchandise_provider_id)');
        $this->addSql('CREATE INDEX IDX_FD0C7178F8BD700D ON merchandise_provider_unit (unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit.factor_to_base IS \'Hệ số quy đổi ra base unit\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit.level IS \'Cấp độ đơn vị\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit.label IS \'Ví dụ: Thùng 16 chai, Lốc 4 chai\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit.is_base IS \'Có phải đơn vị gốc không\'');
        $this->addSql('CREATE TABLE merchandise_provider_unit_conversion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_value NUMERIC(10, 2) DEFAULT \'1.00\' NOT NULL, to_value NUMERIC(10, 2) NOT NULL, sort_order INT DEFAULT 0, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, merchandise_provider_id INT NOT NULL, from_unit_id INT NOT NULL, to_unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1EA78A380455FD2 ON merchandise_provider_unit_conversion (merchandise_provider_id)');
        $this->addSql('CREATE INDEX IDX_1EA78A37EE393A2 ON merchandise_provider_unit_conversion (from_unit_id)');
        $this->addSql('CREATE INDEX IDX_1EA78A376254DF8 ON merchandise_provider_unit_conversion (to_unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit_conversion.from_value IS \'Giá trị quy đổi từ (thường là 1)\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit_conversion.to_value IS \'Giá trị quy đổi sang\'');
        $this->addSql('COMMENT ON COLUMN merchandise_provider_unit_conversion.sort_order IS \'Thứ tự sắp xếp\'');
        $this->addSql('CREATE TABLE merchandise_unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, factor_to_base NUMERIC(10, 4) NOT NULL, level INT DEFAULT 0 NOT NULL, label VARCHAR(255) DEFAULT NULL, is_base BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, merchandise_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_69356D64CFC6D428 ON merchandise_unit (merchandise_id)');
        $this->addSql('CREATE INDEX IDX_69356D64F8BD700D ON merchandise_unit (unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_unit.factor_to_base IS \'Hệ số quy đổi ra base unit (1 đơn vị này = bao nhiêu base unit)\'');
        $this->addSql('COMMENT ON COLUMN merchandise_unit.level IS \'base = 0, càng lớn càng là đơn vị lớn\'');
        $this->addSql('COMMENT ON COLUMN merchandise_unit.label IS \'Ví dụ: Thùng 36 chai\'');
        $this->addSql('COMMENT ON COLUMN merchandise_unit.is_base IS \'true nếu là base unit\'');
        $this->addSql('CREATE TABLE merchandise_unit_conversion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_value NUMERIC(10, 2) DEFAULT \'1.00\' NOT NULL, to_value NUMERIC(10, 2) NOT NULL, sort_order INT DEFAULT 0, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, merchandise_id INT NOT NULL, from_unit_id INT NOT NULL, to_unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B1CC834BCFC6D428 ON merchandise_unit_conversion (merchandise_id)');
        $this->addSql('CREATE INDEX IDX_B1CC834B7EE393A2 ON merchandise_unit_conversion (from_unit_id)');
        $this->addSql('CREATE INDEX IDX_B1CC834B76254DF8 ON merchandise_unit_conversion (to_unit_id)');
        $this->addSql('COMMENT ON COLUMN merchandise_unit_conversion.from_value IS \'Đơn vị quy đổi từ (thường là 1)\'');
        $this->addSql('COMMENT ON COLUMN merchandise_unit_conversion.to_value IS \'Số lượng quy đổi sang\'');
        $this->addSql('COMMENT ON COLUMN merchandise_unit_conversion.sort_order IS \'Thứ tự hiển thị UI\'');
        $this->addSql('ALTER TABLE merchandise ADD CONSTRAINT FK_D043D1A412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise ADD CONSTRAINT FK_D043D1A4CCBBC969 FOREIGN KEY (base_unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider ADD CONSTRAINT FK_A826E055CFC6D428 FOREIGN KEY (merchandise_id) REFERENCES merchandise (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider ADD CONSTRAINT FK_A826E055A53A8AA FOREIGN KEY (provider_id) REFERENCES provider (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider ADD CONSTRAINT FK_A826E0556C9A7223 FOREIGN KEY (default_purchase_unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider_price ADD CONSTRAINT FK_66556CE480455FD2 FOREIGN KEY (merchandise_provider_id) REFERENCES merchandise_provider (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider_price ADD CONSTRAINT FK_66556CE4F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider_unit ADD CONSTRAINT FK_FD0C717880455FD2 FOREIGN KEY (merchandise_provider_id) REFERENCES merchandise_provider (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider_unit ADD CONSTRAINT FK_FD0C7178F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion ADD CONSTRAINT FK_1EA78A380455FD2 FOREIGN KEY (merchandise_provider_id) REFERENCES merchandise_provider (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion ADD CONSTRAINT FK_1EA78A37EE393A2 FOREIGN KEY (from_unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion ADD CONSTRAINT FK_1EA78A376254DF8 FOREIGN KEY (to_unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_unit ADD CONSTRAINT FK_69356D64CFC6D428 FOREIGN KEY (merchandise_id) REFERENCES merchandise (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_unit ADD CONSTRAINT FK_69356D64F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_unit_conversion ADD CONSTRAINT FK_B1CC834BCFC6D428 FOREIGN KEY (merchandise_id) REFERENCES merchandise (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_unit_conversion ADD CONSTRAINT FK_B1CC834B7EE393A2 FOREIGN KEY (from_unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchandise_unit_conversion ADD CONSTRAINT FK_B1CC834B76254DF8 FOREIGN KEY (to_unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_branch_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BRANCH_CODE ON branch (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_category_slug');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORY_SLUG ON category (slug) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_department_ma_bo_phan');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DEPARTMENT_MA_BO_PHAN ON department (ma_bo_phan) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_position_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_CODE ON "position" (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_provider_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROVIDER_CODE ON provider (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_unit_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_UNIT_CODE ON unit (code) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_user_phone');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('DROP INDEX uniq_user_ma_nhan_vien');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_PHONE ON "user" (phone) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email) WHERE deleted_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_MA_NHAN_VIEN ON "user" (ma_nhan_vien) WHERE deleted_at IS NULL');
        $this->addSql('DROP INDEX uniq_warehouse_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WAREHOUSE_CODE ON warehouse (code) WHERE deleted_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE merchandise DROP CONSTRAINT FK_D043D1A412469DE2');
        $this->addSql('ALTER TABLE merchandise DROP CONSTRAINT FK_D043D1A4CCBBC969');
        $this->addSql('ALTER TABLE merchandise_provider DROP CONSTRAINT FK_A826E055CFC6D428');
        $this->addSql('ALTER TABLE merchandise_provider DROP CONSTRAINT FK_A826E055A53A8AA');
        $this->addSql('ALTER TABLE merchandise_provider DROP CONSTRAINT FK_A826E0556C9A7223');
        $this->addSql('ALTER TABLE merchandise_provider_price DROP CONSTRAINT FK_66556CE480455FD2');
        $this->addSql('ALTER TABLE merchandise_provider_price DROP CONSTRAINT FK_66556CE4F8BD700D');
        $this->addSql('ALTER TABLE merchandise_provider_unit DROP CONSTRAINT FK_FD0C717880455FD2');
        $this->addSql('ALTER TABLE merchandise_provider_unit DROP CONSTRAINT FK_FD0C7178F8BD700D');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion DROP CONSTRAINT FK_1EA78A380455FD2');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion DROP CONSTRAINT FK_1EA78A37EE393A2');
        $this->addSql('ALTER TABLE merchandise_provider_unit_conversion DROP CONSTRAINT FK_1EA78A376254DF8');
        $this->addSql('ALTER TABLE merchandise_unit DROP CONSTRAINT FK_69356D64CFC6D428');
        $this->addSql('ALTER TABLE merchandise_unit DROP CONSTRAINT FK_69356D64F8BD700D');
        $this->addSql('ALTER TABLE merchandise_unit_conversion DROP CONSTRAINT FK_B1CC834BCFC6D428');
        $this->addSql('ALTER TABLE merchandise_unit_conversion DROP CONSTRAINT FK_B1CC834B7EE393A2');
        $this->addSql('ALTER TABLE merchandise_unit_conversion DROP CONSTRAINT FK_B1CC834B76254DF8');
        $this->addSql('DROP TABLE merchandise');
        $this->addSql('DROP TABLE merchandise_provider');
        $this->addSql('DROP TABLE merchandise_provider_price');
        $this->addSql('DROP TABLE merchandise_provider_unit');
        $this->addSql('DROP TABLE merchandise_provider_unit_conversion');
        $this->addSql('DROP TABLE merchandise_unit');
        $this->addSql('DROP TABLE merchandise_unit_conversion');
        $this->addSql('DROP INDEX UNIQ_BRANCH_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_branch_code ON branch (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_CATEGORY_SLUG');
        $this->addSql('CREATE UNIQUE INDEX uniq_category_slug ON category (slug) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_DEPARTMENT_MA_BO_PHAN');
        $this->addSql('CREATE UNIQUE INDEX uniq_department_ma_bo_phan ON department (ma_bo_phan) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_POSITION_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_code ON "position" (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_PROVIDER_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_provider_code ON provider (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_UNIT_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_unit_code ON unit (code) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('DROP INDEX UNIQ_USER_MA_NHAN_VIEN');
        $this->addSql('DROP INDEX UNIQ_USER_PHONE');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_ma_nhan_vien ON "user" (ma_nhan_vien) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_phone ON "user" (phone) WHERE (deleted_at IS NULL)');
        $this->addSql('DROP INDEX UNIQ_WAREHOUSE_CODE');
        $this->addSql('CREATE UNIQUE INDEX uniq_warehouse_code ON warehouse (code) WHERE (deleted_at IS NULL)');
    }
}
