<?php

declare(strict_types=1);

return [
    [
        "name" => "general-settings",
        "actions" => [
            "index" => true,
            "edit" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "edit" => t("permission.actions.edit"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "working-times",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "users",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "export" => true,
            "import" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "export" => t("permission.actions.export"),
            "import" => t("permission.actions.import"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "vai-tro",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "departments",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "notifications",
        "actions" => [
            "index" => true,
            "create" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "work-schedules",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "requests",
        "actions" => [
            "index" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "requests:leave",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "approve" => true,
            "reject" => true,
            "cancel" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "approve" => t("permission.actions.approve"),
            "reject" => t("permission.actions.reject"),
            "cancel" => t("permission.actions.cancel"),
        ],
    ],
    [
        "name" => "requests:stock:stock-in",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "approve" => true,
            "reject" => true,
            "cancel" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "approve" => t("permission.actions.approve"),
            "reject" => t("permission.actions.reject"),
            "cancel" => t("permission.actions.cancel"),
        ],
    ],
    [
        "name" => "requests:stock:production",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "approve" => true,
            "reject" => true,
            "cancel" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "approve" => t("permission.actions.approve"),
            "reject" => t("permission.actions.reject"),
            "cancel" => t("permission.actions.cancel"),
        ],
    ],
    [
        "name" => "requests:stock:stock-transfer",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "approve" => true,
            "reject" => true,
            "cancel" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "approve" => t("permission.actions.approve"),
            "reject" => t("permission.actions.reject"),
            "cancel" => t("permission.actions.cancel"),
        ],
    ],
    [
        "name" => "attendance",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "branch",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "category",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "unit",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "export" => true,
            "import" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "export" => t("permission.actions.export"),
            "import" => t("permission.actions.import"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "provider",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "export" => true,
            "import" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "export" => t("permission.actions.export"),
            "import" => t("permission.actions.import"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "merchandise",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "business-product",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "warehouse",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "stock-receipt",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "production-order",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "dining-table",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "sell-product",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "delete" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "delete" => t("permission.actions.delete"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
    [
        "name" => "sale-order",
        "actions" => [
            "index" => true,
            "create" => true,
            "show" => true,
            "edit" => true,
            "showMenu" => true,
        ],
        "actionLabel" => [
            "index" => t("permission.actions.index"),
            "create" => t("permission.actions.create"),
            "show" => t("permission.actions.show"),
            "edit" => t("permission.actions.edit"),
            "showMenu" => t("permission.actions.showMenu"),
        ],
    ],
];
