export const API_ROUTES_CONFIG = {
    login: "/auth/login",
    verifyOtp: "/auth/verify-otp",
    getMe: "/auth/me",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    changePassword: "/auth/change-password",
    generalSettings: "/general-settings",
    thoiGianLamViec: "/thoi-gian-lam-viec",
    media: {
        upload: "/media/upload",
        getAll: "/media",
        delete: "/media/delete",
        getMediaTrash: "/media/trash",
        restore: "/media/restore",
        deletePermanently: "/media/delete-permanently",
    },
    users: "/users",
    importHistory: "/import-history",
    department: "/departments",
    departmentPermissions: "/departments/permissions",
    notifications: "/notifications",
    conversation: "/conversation",
    message: "/message",
    presence: "/presence",
    workSchedule: "/work-schedule",
};
