export const API_ROUTES_CONFIG = {
    login: "/auth/login",
    verifyOtp: "/auth/verify-otp",
    getMe: "/auth/me",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    changePassword: "/auth/change-password",
    generalSettings: "/general-settings",
    workingTimes: "/working-times",
    media: {
        upload: "/media/upload",
        getAll: "/media",
        delete: "/media/delete",
        getMediaTrash: "/media/trash",
        restore: "/media/restore",
        deletePermanently: "/media/delete-permanently",
    },
    users: "/users",
    importHistory: "/import-history",
    department: "/departments",
    departmentPermissions: "/departments/permissions",
    notifications: "/notifications",
    requestTypes: "/request-types",
    requests: "/requests",
    conversation: "/conversation",
    message: "/message",
    presence: "/presence",
    workSchedules: "/work-schedules",
    attendance: "/attendance",
    attendanceQrDisplayAccess: "/attendance/qr-display-access",
    attendanceQr: "/attendance/qr-attendance",
    branch: "/branch",
    category: "/category",
    unit: "/unit",
    provider: "/provider",
};
