export const NAME_ROUTES_CONFIG = {
    login: "auth.login",
    verifyOtp: "auth.verifyOtp",
    forgotPassword: "auth.forgotPassword",
    changePassword: "auth.changePassword",
    dashboard: "system.dashboard",
    systemConfig: "system.config",
    systemGeneralSettings: "system.generalSettings",
    workingTimes: "system.workingTimes",
    userManagement: "system.userManagement",
    users: "system.users",
    importHistory: "system.importHistory",
    department: "system.department",
    notifications: "system.notifications",
    workSchedules: "system.workSchedules",
};
