export const NAME_ROUTES_CONFIG = {
    login: "auth.login",
    verifyOtp: "auth.verifyOtp",
    forgotPassword: "auth.forgotPassword",
    changePassword: "auth.changePassword",
    dashboard: "system.dashboard",
    systemConfig: "system.config",
    systemGeneralSettings: "system.generalSettings",
    systemConfigWorkingTime: "system.configWorkingTime",
    userManagement: "system.userManagement",
    userManagementUser: "system.userManagementUser",
    importHistory: "system.importHistory",
    department: "system.department",
    notifications: "system.notifications",
    workSchedule: "system.workSchedule",
};
